In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series(np.random.uniform(size=9),
   ....:                  index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
   ....:                         [1, 2, 3, 1, 3, 1, 2, 2, 3]])

In [3]:
data

a  1    0.034661
   2    0.694747
   3    0.305049
b  1    0.197145
   3    0.570517
c  1    0.177429
   2    0.559790
d  2    0.789246
   3    0.939939
dtype: float64

In [4]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [7]:
data.loc[:, 2]

a    0.694747
c    0.559790
d    0.789246
dtype: float64

In [9]:
data.unstack().stack()

a  1    0.034661
   2    0.694747
   3    0.305049
b  1    0.197145
   3    0.570517
c  1    0.177429
   2    0.559790
d  2    0.789246
   3    0.939939
dtype: float64

In [12]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
   ....:                      index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
   ....:                      columns=[["Ohio", "Ohio", "Colorado"],
   ....:                               ["Green", "Red", "Green"]])

In [13]:
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [14]:
frame.index.names = ['key1', 'key2']

In [15]:
frame.columns.names = ['state','color']

In [16]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [17]:
frame.index.nlevels

2

In [19]:
frame['Ohio']

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [32]:
frame.loc[('a',1), ("Ohio", "Red")]

np.int64(1)

In [33]:
pd.MultiIndex.from_arrays([["Ohio", "Ohio", "Colorado"],
                          ["Green", "Red", "Green"]],
                          names=["state", "color"])

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

In [34]:
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [35]:
frame.sort_index(level= 1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [39]:
frame.swaplevel(0,1).sort_index(level= 0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [40]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [42]:
frame.groupby(level= 'key2').sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [43]:
frame.groupby(level = 'color', axis= 'columns').sum()

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_8381/3267046616.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level = 'color', axis= 'columns').sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [45]:
frame.T.groupby(level= 'color').sum()

key1   a      b
key2   1  2   1   2
color
Green  2  8  14  20
Red    1  4   7  10

In [46]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
   ....:                       "c": ["one", "one", "one", "two", "two",
   ....:                             "two", "two"],
   ....:                       "d": [0, 1, 2, 0, 1, 2, 3]})

In [47]:
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [48]:
frame2 = frame.set_index(['c','d'])

In [49]:
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [50]:
frame.set_index(['c','d'], drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [51]:
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [52]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
   ....:                     "data1": pd.Series(range(7), dtype="Int64")})

In [53]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [54]:
df2 = pd.DataFrame({"key": ["a", "b", "d"],
   ....:                     "data2": pd.Series(range(3), dtype="Int64")})

In [55]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [57]:
pd.merge(df1, df2, on = 'key')

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [58]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
   ....:                     "data1": pd.Series(range(7), dtype="Int64")})

In [59]:
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [60]:
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
   ....:                     "data2": pd.Series(range(3), dtype="Int64")})

In [61]:
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [63]:
pd.merge(df3, df4, left_on= 'lkey', right_on='rkey', how= 'outer')

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In [64]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
   ....:                      "key2": ["one", "two", "one"],
   ....:                      "lval": pd.Series([1, 2, 3], dtype='Int64')})

In [65]:
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
   ....:                       "key2": ["one", "one", "one", "two"],
   ....:                       "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})

In [67]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [69]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [71]:
pd.merge(left,right, on = ['key1', 'key2'], how= 'outer')

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [75]:
pd.merge(left, right, on = 'key1', suffixes= ('_left', '_right'))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [76]:
left1 = pd.DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
   ....:                       "value": pd.Series(range(6), dtype="Int64")})

In [77]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [78]:
right1 = pd.DataFrame({"group_val": [3.5, 7]}, index=["a", "b"])

In [79]:
right1

   group_val
a        3.5
b        7.0

In [80]:
pd.merge(left1, right1, left_on= 'key', right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [81]:
lefth = pd.DataFrame({"key1": ["Ohio", "Ohio", "Ohio",
   ....:                                "Nevada", "Nevada"],
   ....:                       "key2": [2000, 2001, 2002, 2001, 2002],
   ....:                       "data": pd.Series(range(5), dtype="Int64")})

In [82]:
lefth

     key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [84]:
righth_index = pd.MultiIndex.from_arrays(
   ....:     [
   ....:         ["Nevada", "Nevada", "Ohio", "Ohio", "Ohio", "Ohio"],
   ....:         [2001, 2000, 2000, 2000, 2001, 2002]
   ....:     ]
   ....: )

In [85]:
righth_index

MultiIndex([('Nevada', 2001),
            ('Nevada', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2001),
            (  'Ohio', 2002)],
           )

In [87]:
righth = pd.DataFrame({"event1": pd.Series([0, 2, 4, 6, 8, 10], dtype="Int64",
   ....:                                            index=righth_index),
   ....:                        "event2": pd.Series([1, 3, 5, 7, 9, 11], dtype="Int64",
   ....:                                            index=righth_index)})

In [88]:
righth

             event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [90]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True, how = 'outer')

     key1  key2  data  event1  event2
4  Nevada  2000  <NA>       2       3
3  Nevada  2001     3       0       1
4  Nevada  2002     4    <NA>    <NA>
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11

In [91]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
   ....:                        index=["a", "c", "e", "f"],
   ....:                        columns=["New York", "Oregon"])

In [92]:
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [93]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
   ....:                       index=["b", "c", "d", "e"],
   ....:                       columns=["Missouri", "Alabama"]).astype("Int64")

In [94]:
right2

   Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [95]:
[right2, another]

[   Missouri  Alabama
 b         7        8
 c         9       10
 d        11       12
 e        13       14,
    New York  Oregon
 a       7.0     8.0
 c       9.0    10.0
 e      11.0    12.0
 f      16.0    17.0]

In [96]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
   ....:                      index=["a", "c", "e"],
   ....:                      columns=["Ohio", "Nevada"]).astype("Int64")

In [97]:
left2

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [99]:
left2.join([right2, another], how = "outer")

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0
b  <NA>    <NA>         7        8       NaN     NaN
d  <NA>    <NA>        11       12       NaN     NaN
f  <NA>    <NA>      <NA>     <NA>      16.0    17.0

In [100]:
#concatenating

In [101]:
arr = np.arange(12).reshape((3,4))

In [102]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
np.concat([arr,arr], axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [105]:
In [87]: s1 = pd.Series([0, 1], index=["a", "b"], dtype="Int64")

In [88]: s2 = pd.Series([2, 3, 4], index=["c", "d", "e"], dtype="Int64")

In [89]: s3 = pd.Series([5, 6], index=["f", "g"], dtype="Int64")

In [106]:
s1

a    0
b    1
dtype: Int64

In [107]:
s2

c    2
d    3
e    4
dtype: Int64

In [108]:
s3

f    5
g    6
dtype: Int64

In [111]:
pd.concat([s1,s2,s3], axis= 1)

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [112]:
s4 = pd.concat([s1, s3])

In [113]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [115]:
pd.concat([s1, s4], axis= 1, join = 'inner')

   0  1
a  0  0
b  1  1

In [121]:
result = pd.concat([s1, s2, s3], axis = 1, keys=["one", "two", "three"])

In [122]:
result

    one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [124]:
result.stack()

a  one      0
b  one      1
c  two      2
d  two      3
e  two      4
f  three    5
g  three    6
dtype: Int64

In [125]:
In [103]: df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=["a", "b", "c"],
   .....:                    columns=["one", "two"])

In [104]: df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=["a", "c"],
   .....:                    columns=["three", "four"])

In [126]:
df1

   one  two
a    0    1
b    2    3
c    4    5

In [127]:
df2

   three  four
a      5     6
c      7     8

In [134]:
pd.concat([df1, df2], axis= 1, keys= ['level1', 'level2'])

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [136]:
pd.concat(
    {'level1':df1, 'level2':df2}, axis=1
)

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [137]:
In [110]: df1 = pd.DataFrame(np.random.standard_normal((3, 4)),
   .....:                    columns=["a", "b", "c", "d"])

In [111]: df2 = pd.DataFrame(np.random.standard_normal((2, 3)),
   .....:                    columns=["b", "d", "a"])

In [138]:
pd.concat([df1, df2], ignore_index= True)

          a         b         c         d
0  0.061809  0.001932 -1.593712  1.444646
1  0.474192  1.854311  1.400892  0.146119
2 -0.533880  0.690900  0.653627 -0.029393
3 -0.865029  0.727172       NaN  0.443241
4  0.499662 -1.851868       NaN  0.074391

In [139]:
In [115]: a = pd.Series([np.nan, 2.5, 0.0, 3.5, 4.5, np.nan],
   .....:               index=["f", "e", "d", "c", "b", "a"])

In [116]: b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
   .....:               index=["a", "b", "c", "d", "e", "f"])

In [140]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [141]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [144]:
np.where(pd.isna(a), b ,a ) # doesn't check the index

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [145]:
a.combine_first(b) #check the index alignment

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

In [146]:
df1 = pd.DataFrame({"a": [1., np.nan, 5., np.nan],
   .....:                     "b": [np.nan, 2., np.nan, 6.],
   .....:                     "c": range(2, 18, 4)})

In [147]:
df1

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [148]:
df2 = pd.DataFrame({"a": [5., 4., np.nan, 3., 7.],
   .....:                     "b": [np.nan, 3., 4., 6., 8.]})

In [149]:
df2

     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [151]:
df1.combine_first(df2) # union of all column names

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [153]:
#reshaping and pivoting

In [154]:
In [126]: data = pd.DataFrame(np.arange(6).reshape((2, 3)),
   .....:                     index=pd.Index(["Ohio", "Colorado"], name="state"),
   .....:                     columns=pd.Index(["one", "two", "three"],
   .....:                     name="number"))

In [155]:
data

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [156]:
result = data.stack()

In [157]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [158]:
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [161]:
result.unstack(level = 'state')

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [162]:
In [133]: s1 = pd.Series([0, 1, 2, 3], index=["a", "b", "c", "d"], dtype="Int64")

In [134]: s2 = pd.Series([4, 5, 6], index=["c", "d", "e"], dtype="Int64")

In [163]:
s1

a    0
b    1
c    2
d    3
dtype: Int64

In [164]:
s2

c    4
d    5
e    6
dtype: Int64

In [165]:
data2 = pd.concat([s1,s2],keys= ['one','two'])

In [166]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [172]:
data2.unstack().stack(future_stack=True)

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

In [173]:
df = pd.DataFrame({"left": result, "right": result + 5},
   .....:                   columns=pd.Index(["left", "right"], name="side"))

In [174]:
df

side             left  right
state    number
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [178]:
df.unstack(level= "state").stack(level = 'side', future_stack = True)

state         Ohio  Colorado
number side
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

In [195]:
#pivot long to wide

In [196]:
data = pd.read_csv("../examples/macrodata.csv")

In [197]:
data

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959,1,2710.349,1707.4,286.898,470.045,1886.9,28.980,139.7,2.82,5.8,177.146,0.00,0.00
1,1959,2,2778.801,1733.7,310.859,481.301,1919.7,29.150,141.7,3.08,5.1,177.830,2.34,0.74
2,1959,3,2775.488,1751.8,289.226,491.260,1916.4,29.350,140.5,3.82,5.3,178.657,2.74,1.09
3,1959,4,2785.204,1753.7,299.356,484.052,1931.3,29.370,140.0,4.33,5.6,179.386,0.27,4.06
4,1960,1,2847.699,1770.5,331.722,462.199,1955.5,29.540,139.6,3.50,5.2,180.007,2.31,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,2008,3,13324.600,9267.7,1990.693,991.551,9838.3,216.889,1474.7,1.17,6.0,305.270,-3.16,4.33
199,2008,4,13141.920,9195.3,1857.661,1007.273,9920.4,212.174,1576.5,0.12,6.9,305.952,-8.79,8.91
200,2009,1,12925.410,9209.2,1558.494,996.287,9926.4,212.671,1592.8,0.22,8.1,306.547,0.94,-0.71
201,2009,2,12901.504,9189.0,1456.678,1023.528,10077.5,214.469,1653.6,0.18,9.2,307.226,3.37,-3.19
202,2009,3,12990.341,9256.0,1486.398,1044.088,10040.6,216.385,1673.9,0.12,9.6,308.013,3.56,-3.44

In [198]:
data = data.loc[:, ["year", "quarter", "realgdp", "infl", "unemp"]]

In [199]:
data

     year  quarter    realgdp  infl  unemp
0    1959        1   2710.349  0.00    5.8
1    1959        2   2778.801  2.34    5.1
2    1959        3   2775.488  2.74    5.3
3    1959        4   2785.204  0.27    5.6
4    1960        1   2847.699  2.31    5.2
..    ...      ...        ...   ...    ...
198  2008        3  13324.600 -3.16    6.0
199  2008        4  13141.920 -8.79    6.9
200  2009        1  12925.410  0.94    8.1
201  2009        2  12901.504  3.37    9.2
202  2009        3  12990.341  3.56    9.6

[203 rows x 5 columns]

In [200]:
data.head()

   year  quarter   realgdp  infl  unemp
0  1959        1  2710.349  0.00    5.8
1  1959        2  2778.801  2.34    5.1
2  1959        3  2775.488  2.74    5.3
3  1959        4  2785.204  0.27    5.6
4  1960        1  2847.699  2.31    5.2

In [201]:
data.columns

Index(['year', 'quarter', 'realgdp', 'infl', 'unemp'], dtype='object')

In [202]:
data.index

RangeIndex(start=0, stop=203, step=1)

In [203]:
periods = pd.PeriodIndex(
    year = data.pop('year'),
    quarter = data.pop('quarter'),
    name = 'date'
)

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_8381/1186568624.py:1: FutureWarning: Constructing PeriodIndex from fields is deprecated. Use PeriodIndex.from_fields instead.
  periods = pd.PeriodIndex(

In [204]:
periods

PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4', '1960Q1', '1960Q2',
             '1960Q3', '1960Q4', '1961Q1', '1961Q2',
             ...
             '2007Q2', '2007Q3', '2007Q4', '2008Q1', '2008Q2', '2008Q3',
             '2008Q4', '2009Q1', '2009Q2', '2009Q3'],
            dtype='period[Q-DEC]', name='date', length=203)

In [205]:
data.index = periods.to_timestamp('D')

In [206]:
data.head()

             realgdp  infl  unemp
date
1959-01-01  2710.349  0.00    5.8
1959-04-01  2778.801  2.34    5.1
1959-07-01  2775.488  2.74    5.3
1959-10-01  2785.204  0.27    5.6
1960-01-01  2847.699  2.31    5.2

In [207]:
data = data.reindex(columns = ["realgdp", "infl", "unemp"])

In [210]:
data.columns.name = "item"

In [211]:
data.columns

Index(['realgdp', 'infl', 'unemp'], dtype='object', name='item')

In [212]:
data.head()

item         realgdp  infl  unemp
date
1959-01-01  2710.349  0.00    5.8
1959-04-01  2778.801  2.34    5.1
1959-07-01  2775.488  2.74    5.3
1959-10-01  2785.204  0.27    5.6
1960-01-01  2847.699  2.31    5.2

In [218]:
long_data = data.stack().reset_index().rename(columns = {0:"value"})

In [219]:
long_data

          date     item      value
0   1959-01-01  realgdp   2710.349
1   1959-01-01     infl      0.000
2   1959-01-01    unemp      5.800
3   1959-04-01  realgdp   2778.801
4   1959-04-01     infl      2.340
..         ...      ...        ...
604 2009-04-01     infl      3.370
605 2009-04-01    unemp      9.200
606 2009-07-01  realgdp  12990.341
607 2009-07-01     infl      3.560
608 2009-07-01    unemp      9.600

[609 rows x 3 columns]

In [220]:
#pivot function
pivoted = long_data.pivot(index= 'date', columns= 'item', values= 'value')

In [221]:
pivoted

item        infl    realgdp  unemp
date
1959-01-01  0.00   2710.349    5.8
1959-04-01  2.34   2778.801    5.1
1959-07-01  2.74   2775.488    5.3
1959-10-01  0.27   2785.204    5.6
1960-01-01  2.31   2847.699    5.2
...          ...        ...    ...
2008-07-01 -3.16  13324.600    6.0
2008-10-01 -8.79  13141.920    6.9
2009-01-01  0.94  12925.410    8.1
2009-04-01  3.37  12901.504    9.2
2009-07-01  3.56  12990.341    9.6

[203 rows x 3 columns]

In [222]:
long_data["value2"] = np.random.standard_normal(len(long_data))

In [223]:
long_data

          date     item      value    value2
0   1959-01-01  realgdp   2710.349  0.631468
1   1959-01-01     infl      0.000 -0.699018
2   1959-01-01    unemp      5.800 -0.291421
3   1959-04-01  realgdp   2778.801  0.432349
4   1959-04-01     infl      2.340  0.218365
..         ...      ...        ...       ...
604 2009-04-01     infl      3.370 -0.638007
605 2009-04-01    unemp      9.200 -0.367748
606 2009-07-01  realgdp  12990.341  0.151766
607 2009-07-01     infl      3.560 -1.650595
608 2009-07-01    unemp      9.600 -0.668236

[609 rows x 4 columns]

In [224]:
pivoted = long_data.pivot(index= 'date', columns= 'item')

In [225]:
pivoted

           value                     value2
item        infl    realgdp unemp      infl   realgdp     unemp
date
1959-01-01  0.00   2710.349   5.8 -0.699018  0.631468 -0.291421
1959-04-01  2.34   2778.801   5.1  0.218365  0.432349 -0.662987
1959-07-01  2.74   2775.488   5.3 -0.711859  0.575012 -2.271481
1959-10-01  0.27   2785.204   5.6 -0.472772 -0.391994  0.493737
1960-01-01  2.31   2847.699   5.2  1.644964  0.249963 -1.343379
...          ...        ...   ...       ...       ...       ...
2008-07-01 -3.16  13324.600   6.0  0.971663 -0.287210 -0.401026
2008-10-01 -8.79  13141.920   6.9  0.447693  0.417937  0.075654
2009-01-01  0.94  12925.410   8.1  0.297854  0.906303  0.284101
2009-04-01  3.37  12901.504   9.2 -0.638007 -0.443656 -0.367748
2009-07-01  3.56  12990.341   9.6 -1.650595  0.151766 -0.668236

[203 rows x 6 columns]

In [226]:
pivoted['value']

item        infl    realgdp  unemp
date
1959-01-01  0.00   2710.349    5.8
1959-04-01  2.34   2778.801    5.1
1959-07-01  2.74   2775.488    5.3
1959-10-01  0.27   2785.204    5.6
1960-01-01  2.31   2847.699    5.2
...          ...        ...    ...
2008-07-01 -3.16  13324.600    6.0
2008-10-01 -8.79  13141.920    6.9
2009-01-01  0.94  12925.410    8.1
2009-04-01  3.37  12901.504    9.2
2009-07-01  3.56  12990.341    9.6

[203 rows x 3 columns]

In [229]:
long_data.set_index(['date', 'item']).unstack(level= 'item')

           value                     value2
item        infl    realgdp unemp      infl   realgdp     unemp
date
1959-01-01  0.00   2710.349   5.8 -0.699018  0.631468 -0.291421
1959-04-01  2.34   2778.801   5.1  0.218365  0.432349 -0.662987
1959-07-01  2.74   2775.488   5.3 -0.711859  0.575012 -2.271481
1959-10-01  0.27   2785.204   5.6 -0.472772 -0.391994  0.493737
1960-01-01  2.31   2847.699   5.2  1.644964  0.249963 -1.343379
...          ...        ...   ...       ...       ...       ...
2008-07-01 -3.16  13324.600   6.0  0.971663 -0.287210 -0.401026
2008-10-01 -8.79  13141.920   6.9  0.447693  0.417937  0.075654
2009-01-01  0.94  12925.410   8.1  0.297854  0.906303  0.284101
2009-04-01  3.37  12901.504   9.2 -0.638007 -0.443656 -0.367748
2009-07-01  3.56  12990.341   9.6 -1.650595  0.151766 -0.668236

[203 rows x 6 columns]

In [230]:
#wide to long

In [231]:
In [167]: df = pd.DataFrame({"key": ["foo", "bar", "baz"],
   .....:                    "A": [1, 2, 3],
   .....:                    "B": [4, 5, 6],
   .....:                    "C": [7, 8, 9]})

In [232]:
df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [236]:
melted = pd.melt(df, id_vars= 'key')

In [237]:
melted

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [239]:
reshape = melted.pivot(index= 'key', columns= 'variable', values= 'value')

In [240]:
reshape

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [241]:
reshape.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [244]:
df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [243]:
pd.melt(df, id_vars= "key", value_vars=['A', 'B'])

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [245]:
pd.melt(df, value_vars=["A", "B", "C"])

  variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9

In [246]:
pd.melt(df, value_vars=["key", "A", "B"])

  variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6