In [1]:
import numpy as np
import pandas as pd

In [2]:
float_data  = pd.Series([1.2, -3.5, np.nan, 0])

In [3]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [6]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [7]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [9]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
   ....:                      [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [13]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how = "all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4] = np.nan

In [17]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [19]:
data.dropna(axis= 'columns', how= "all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [21]:
df

          0         1         2
0  0.346911  0.552178 -0.662705
1  1.198491  0.352802 -0.232543
2  0.401484  0.757206 -0.593510
3 -2.184147  0.167930  1.152127
4  0.363042  1.120239 -1.761055
5  0.054134  0.351588  0.182748
6  0.592912 -0.112513 -0.694967

In [22]:
df.iloc[:4, 1] = np.nan

In [23]:
df

          0         1         2
0  0.346911       NaN -0.662705
1  1.198491       NaN -0.232543
2  0.401484       NaN -0.593510
3 -2.184147       NaN  1.152127
4  0.363042  1.120239 -1.761055
5  0.054134  0.351588  0.182748
6  0.592912 -0.112513 -0.694967

In [24]:
df.iloc[:2, 2] = np.nan

In [25]:
df

          0         1         2
0  0.346911       NaN       NaN
1  1.198491       NaN       NaN
2  0.401484       NaN -0.593510
3 -2.184147       NaN  1.152127
4  0.363042  1.120239 -1.761055
5  0.054134  0.351588  0.182748
6  0.592912 -0.112513 -0.694967

In [27]:
df.dropna(thresh= 2)

          0         1         2
2  0.401484       NaN -0.593510
3 -2.184147       NaN  1.152127
4  0.363042  1.120239 -1.761055
5  0.054134  0.351588  0.182748
6  0.592912 -0.112513 -0.694967

In [28]:
df.fillna(0)

          0         1         2
0  0.346911  0.000000  0.000000
1  1.198491  0.000000  0.000000
2  0.401484  0.000000 -0.593510
3 -2.184147  0.000000  1.152127
4  0.363042  1.120239 -1.761055
5  0.054134  0.351588  0.182748
6  0.592912 -0.112513 -0.694967

In [29]:
df.fillna({1:0.5, 2:0})

          0         1         2
0  0.346911  0.500000  0.000000
1  1.198491  0.500000  0.000000
2  0.401484  0.500000 -0.593510
3 -2.184147  0.500000  1.152127
4  0.363042  1.120239 -1.761055
5  0.054134  0.351588  0.182748
6  0.592912 -0.112513 -0.694967

In [34]:
df.bfill(limit= 2)

          0         1         2
0  0.346911       NaN -0.593510
1  1.198491       NaN -0.593510
2  0.401484  1.120239 -0.593510
3 -2.184147  1.120239  1.152127
4  0.363042  1.120239 -1.761055
5  0.054134  0.351588  0.182748
6  0.592912 -0.112513 -0.694967

In [35]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
   ....:                      "k2": [1, 1, 2, 3, 3, 4, 4]})

In [36]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [37]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [38]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [39]:
data['v1'] = range(7)

In [40]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [42]:
data.drop_duplicates(subset= ['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [44]:
data.drop_duplicates(['k1', 'k2'], keep= 'last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [45]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
   ....:                               "pastrami", "corned beef", "bacon",
   ....:                               "pastrami", "honey ham", "nova lox"],
   ....:                      "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [46]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [47]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [48]:
data['animal'] = data['food'].map(meat_to_animal)

In [49]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [51]:
def get_animal(x):
    return meat_to_animal[x]

In [52]:
data['food'].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [53]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [54]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace([-999,-1000], [np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
data.replace(
    {
        -999: np.nan,
        -1000:0
    }
)

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
   ....:                     index=["Ohio", "Colorado", "New York"],
   ....:                     columns=["one", "two", "three", "four"])

In [60]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [61]:
def transform(x):
    return x[:4].upper()

In [64]:
data.index = data.index.map(transform)

In [65]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [66]:
data.rename(index = str.title, columns= str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [68]:
data.rename(
    index= {'OHIO': 'INDIANA'},
    columns= {"three": "peekaboo"}
)

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [75]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [76]:
ages

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [77]:
bins = [18, 25, 35, 60, 100]

In [78]:
age_cat = pd.cut(ages, bins)

In [79]:
age_cat

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [80]:
age_cat.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [81]:
age_cat.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [83]:
age_cat.categories[0]

Interval(18, 25, closed='right')

In [90]:
age_cat.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [91]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [92]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [93]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [94]:
data = np.random.uniform(size=20)

In [95]:
data

array([0.14586462, 0.88213713, 0.03363717, 0.41365454, 0.48705485,
       0.36986588, 0.23157448, 0.88752202, 0.69753177, 0.85468093,
       0.51494557, 0.35286974, 0.23928458, 0.27206977, 0.04245802,
       0.61881133, 0.10907983, 0.30542868, 0.44101308, 0.51566721])

In [96]:
pd.cut(data, 4, precision= 2)

[(0.033, 0.25], (0.67, 0.89], (0.033, 0.25], (0.25, 0.46], (0.46, 0.67], ..., (0.46, 0.67], (0.033, 0.25], (0.25, 0.46], (0.25, 0.46], (0.46, 0.67]]
Length: 20
Categories (4, interval[float64, right]): [(0.033, 0.25] < (0.25, 0.46] < (0.46, 0.67] < (0.67, 0.89]]

In [97]:
data = np.random.standard_normal(1000)

In [98]:
data

array([ 9.89126011e-01,  7.47263530e-01,  1.46109773e+00, -1.20716704e+00,
       -1.35051911e-01,  2.14621174e+00,  4.52595871e-01,  8.60045901e-01,
       -2.04101242e+00,  7.01472503e-01,  6.95340197e-01,  7.30139089e-01,
       -1.45290413e-01,  4.24279872e-01,  1.30562677e+00,  7.48195950e-01,
        7.97131615e-01,  5.91215775e-01,  1.01668587e-01, -5.36715107e-01,
        2.41314933e+00, -1.12188092e+00, -1.31946300e+00,  8.44368544e-01,
       -7.30812660e-01, -3.42249988e-02, -1.77952982e+00, -3.99282054e-01,
        1.17029773e+00, -8.35951663e-01, -1.85217061e-01,  7.42378204e-01,
       -1.39732862e+00,  7.89133550e-01, -8.19401227e-01, -3.23177213e-01,
        2.08029504e+00, -1.15056029e+00,  7.69706960e-02, -1.23924213e-01,
        5.73455634e-01, -1.31107130e+00, -4.50295084e-01, -4.50827710e-01,
        1.51943894e+00, -7.75036595e-03,  1.60468066e+00,  1.10725390e-01,
        5.17363002e-01,  5.09156325e-01,  4.14374765e-01, -1.37055343e+00,
       -2.52756393e+00, -5.47675884e-01,  4.38039813e-01, -1.97179316e+00,
       -6.20173981e-01, -4.17588033e-02, -6.48135873e-01, -3.57117332e-01,
        7.29712459e-01,  2.56983810e-01,  4.62443769e-01, -1.02414296e-01,
       -1.31241180e+00, -7.67150148e-01, -1.44228113e+00,  1.30818903e+00,
       -7.99996507e-01,  7.90905136e-01, -1.97862699e+00, -1.07782607e+00,
       -5.84256183e-02,  6.67931049e-01,  1.60552249e+00, -7.62524161e-01,
       -9.10721527e-01, -7.02382188e-03, -3.67249992e-02,  1.18362990e-01,
        1.34378251e+00,  9.52111953e-01, -8.85140343e-02, -4.62416559e-01,
        4.73614411e-01,  1.70382382e-01,  1.08505564e+00,  1.82834758e-01,
       -6.41918961e-01,  3.23642534e-01, -8.93551327e-02,  1.32648572e-01,
        2.68143746e-01, -1.16031277e-01, -4.81131816e-01,  8.30444819e-01,
       -2.16918725e-01,  5.72183224e-01, -9.83439630e-01,  7.71026473e-01,
        1.97294933e+00,  1.35681601e+00, -1.22633295e+00, -2.90401793e-01,
       -1.83567153e+00, -6.27859748e-01, -5.90155100e-01,  8.55105253e-01,
       -1.97083948e+00, -1.07528113e+00, -7.13032919e-01, -3.18358204e-01,
       -3.52095451e-01, -1.98398887e-01, -7.13862178e-01,  9.62921367e-01,
        7.05685482e-01, -7.59068618e-01,  5.27154857e-02, -7.88939804e-01,
        1.47038727e+00,  1.01632693e+00,  8.91709503e-01, -2.89056928e-01,
        1.12806823e+00,  1.34190817e+00, -4.02184018e-01,  8.03149525e-01,
        2.08595227e-01, -9.60884016e-01,  9.37844512e-01, -1.34974932e+00,
       -1.65907104e+00,  1.39179711e-01, -3.69847456e-01, -2.04022123e+00,
        1.67494353e-01,  5.25382120e-01,  7.32131750e-01, -8.63333143e-02,
       -8.24232404e-01,  9.82768310e-01,  8.08012495e-01, -2.05923071e-01,
       -5.63737479e-01, -2.12737023e-01, -1.49379213e+00, -6.76339985e-01,
        4.15745646e-01, -1.42113203e+00, -2.01929149e+00, -4.12152053e-01,
       -1.45084475e+00,  3.64478510e-01,  9.09664725e-02,  1.40815427e-01,
        6.74037756e-01,  1.15993721e+00,  8.38814324e-01, -6.38576119e-01,
       -4.07197501e-01, -1.14817380e+00, -1.06061316e+00, -9.62830023e-01,
       -1.79054695e+00, -2.08266396e-01,  6.99474694e-01, -1.09810808e-01,
       -9.55319530e-01,  1.48605693e+00,  1.40602346e+00, -1.47955937e+00,
        1.48024153e-01,  6.01733323e-01, -2.75738122e-02,  1.56228574e-01,
        2.44522844e-02, -4.48714139e-01,  1.13085894e+00,  1.00866688e+00,
        4.69937081e-01, -2.87482212e-01, -1.95782871e+00,  3.98265244e-01,
       -6.97605399e-01, -8.00293852e-01, -1.33998016e+00,  1.29312202e+00,
       -9.24038967e-01,  1.15153408e-01, -6.41538547e-02, -1.69850049e+00,
       -6.37296409e-01,  1.67725074e+00, -2.34256431e-01, -4.15926981e-01,
        1.14006715e+00,  2.68507843e-02, -4.63097453e-01, -1.18415070e+00,
       -6.32783131e-01, -6.95019114e-01,  7.82259330e-02, -2.59321527e-01,
       -9.63725825e-01, -8.85141866e-01, -6.69609175e-01,  2.73887985e-01,
        6.46289970e-01, -8.88241546e-01,  8.88218442e-01,  1.30885414e+00,
       -5.68004218e-01, -9.52707102e-01, -7.81504463e-01, -2.79040628e-01,
       -2.43674227e+00, -2.75012036e-01, -6.45351089e-01, -2.44326183e-01,
       -1.06618769e+00, -1.31871673e+00,  4.89139252e-01,  4.85420044e-02,
        3.83403108e-01, -2.28817129e-01, -6.19840237e-01,  6.64827113e-01,
        1.09870367e+00,  6.05400528e-01,  5.68704566e-01,  1.34917817e+00,
        3.23402753e-01, -7.43051004e-01,  2.75694436e-01, -9.28185144e-01,
       -1.57992039e-01, -2.49311877e-01,  1.11881619e+00, -5.99190692e-01,
       -1.61075745e+00, -6.54023709e-01, -8.54313561e-01,  2.83713369e-01,
        1.74868027e+00, -4.87106284e-01,  9.06170267e-01, -1.86015281e+00,
        1.46047762e+00,  1.21108147e+00,  8.80482698e-01, -1.03565886e+00,
        1.80796183e-01,  7.93466862e-01,  1.49726470e-01, -1.95994390e+00,
        9.90414723e-01,  1.79303313e-01, -1.90229385e+00,  9.04772339e-01,
        6.57678641e-02, -1.99808649e-01,  7.09433731e-01, -2.15195829e-01,
        1.25748298e+00, -3.69629308e-02,  9.33773671e-01,  6.48011031e-01,
       -1.61332907e+00, -1.25060425e+00,  1.35848376e-01, -3.65412617e-01,
       -9.75140482e-01,  1.49104434e-01,  9.66609875e-01,  1.34739149e+00,
        3.76556168e-01,  1.10646629e+00, -1.19225426e+00,  4.49552223e-01,
       -7.37823421e-01,  5.01627817e-01,  1.42371212e+00, -7.36700340e-01,
        2.11788858e+00, -1.32394182e+00,  1.44740488e-01,  1.89523968e-01,
        8.59519899e-01, -1.52010748e-02, -6.56930436e-01,  1.40545222e+00,
       -1.11237851e-01, -6.57317573e-01, -8.15982042e-02,  1.31541459e+00,
       -4.31546606e-01, -1.16452243e+00,  4.86295075e-01,  7.24494378e-01,
       -8.57851510e-01,  1.31749622e+00,  5.94313804e-01,  1.00542291e+00,
       -1.74268511e+00, -7.18183068e-01, -1.58422361e-01, -1.96038631e+00,
       -3.86936303e-01, -4.22842006e-01, -1.01828880e+00,  8.43636717e-01,
        3.42562061e-01, -3.58601517e-01,  2.87104187e-01, -1.46573631e-01,
       -7.66781695e-01,  2.43404283e+00, -4.93946354e-01, -1.18155016e-01,
       -8.22377539e-01,  2.66973824e-01,  4.66598770e-01, -1.14549794e-01,
       -3.05419923e-01, -7.42512109e-01, -1.82371724e-01, -1.15989037e+00,
        2.22220386e-01,  8.64531558e-02,  2.18167474e+00,  1.61988353e+00,
       -1.03921205e+00, -9.23551064e-02,  1.39070175e-01,  5.57572348e-01,
       -2.43173620e+00,  8.72345553e-02,  1.37068548e+00,  8.80758847e-01,
       -3.03414554e-01, -1.94872783e+00,  3.04368401e+00,  3.15084870e-02,
        2.06808846e+00,  5.13463446e-01,  5.61944268e-01,  2.88148053e-01,
        7.78774411e-01, -3.69246456e-01,  1.13309136e+00,  5.85173372e-01,
       -5.63833577e-02, -2.38978976e+00,  1.60182888e+00, -1.69334166e+00,
       -1.52872872e+00, -3.88946460e-02,  1.00510747e+00, -5.87554112e-01,
       -1.28834753e+00, -9.03583562e-02, -3.28379709e-01, -9.45731204e-02,
       -1.69323474e+00, -5.00040006e-01, -1.15643830e+00, -6.48792118e-02,
        6.39160037e-02,  7.21952024e-01, -4.37660563e-01, -1.26444409e+00,
        5.67065179e-01, -4.83075010e-01, -4.39974447e-01,  1.49714628e-01,
        3.67921245e-01,  3.47921323e-01,  7.29219598e-01, -7.72113250e-01,
        1.30952874e+00,  6.88096789e-01,  1.07737465e+00, -7.02022395e-01,
       -1.07966374e-01,  7.52738929e-01,  8.00878503e-01, -8.62662574e-01,
       -5.89351601e-01,  1.19268210e+00,  8.33135060e-01,  1.35026320e-01,
       -3.70155811e-01,  7.04623442e-01,  9.76310797e-01, -4.76661123e-01,
       -1.16530222e-01,  1.23147302e+00,  1.08787732e+00,  1.17540789e+00,
       -9.24144479e-01, -1.11172212e-01,  1.56404870e-01,  2.47239732e-01,
        1.18795838e+00, -7.22344623e-01,  1.84519498e+00,  5.82246337e-01,
        1.60501853e+00,  9.54193737e-01, -1.23803065e+00,  7.47469717e-01,
        2.19719367e+00, -7.89733777e-01,  1.00250137e-01, -3.71113102e-01,
        1.14238059e+00, -1.81225635e-01,  8.24637859e-02, -1.57567656e+00,
       -5.00414439e-01, -6.95177389e-02,  1.29642131e+00,  1.04619534e+00,
        1.40984197e+00, -6.98347712e-01,  9.50228275e-01,  4.49359968e-01,
       -7.35377974e-01,  2.13153613e-01,  3.84953552e-01,  3.49813126e-01,
        1.18511644e-01, -9.22398885e-01, -9.86123301e-01,  1.52140072e+00,
        5.09621258e-02,  3.52847574e-01, -2.15946234e-01,  1.22206395e+00,
       -1.53317609e-01,  1.81309807e-01,  1.29418095e+00,  4.32126576e-04,
        3.93332717e-01, -1.95819575e+00,  9.82757343e-01,  1.82104271e+00,
       -4.09201888e-01, -8.76459767e-01,  7.84122319e-01, -3.29531826e-01,
        6.38937444e-01,  4.29629527e-01,  3.77783457e-01,  2.28705268e-01,
       -4.35784479e-03, -6.11361848e-01,  1.49764817e-01, -6.36122517e-01,
       -3.70576359e-01, -3.06005638e+00, -1.60159044e+00, -9.26983131e-01,
        1.49286442e+00,  1.37333002e+00,  7.89555563e-01, -1.62170536e+00,
       -1.33209165e+00,  3.48504268e-01,  1.12037659e+00,  1.66417461e+00,
       -1.17333255e+00, -1.93838346e+00,  2.55812185e+00,  1.09966747e-01,
        1.16328771e+00,  1.24982702e+00,  1.49658353e-02,  7.37226054e-01,
       -1.75084814e-01, -1.01340774e+00, -1.65208273e+00,  3.72078414e-01,
        1.79229281e+00,  1.92307747e-01,  6.35244968e-01, -1.36435745e+00,
        1.15490346e+00,  3.58724178e-01,  2.73073784e-02, -3.26885767e-01,
        1.12694077e+00,  7.22772051e-01, -4.86375166e-01, -1.05684242e+00,
       -1.15424378e+00, -1.73812963e+00, -5.09045023e-01, -2.66447125e+00,
       -7.33047468e-01, -7.93241468e-01, -1.29060483e+00, -2.01669269e-01,
       -9.22333741e-01,  1.48646110e+00,  3.25349591e-01,  1.41043778e+00,
        4.72309137e-01, -6.78961157e-01,  7.05652561e-01, -1.95179447e-01,
       -3.46260951e-01, -6.93684455e-02,  1.23823708e-01,  2.73730204e+00,
        7.21278850e-01, -2.65928682e-01,  1.24804479e-01, -2.06464943e+00,
       -8.25884637e-01,  3.90767706e-01, -6.03624094e-01, -5.83161611e-02,
        4.11377285e-01, -5.03299523e-01,  4.70501771e-01,  7.16276666e-01,
       -1.22378594e+00,  9.52069160e-01, -9.21458327e-01,  9.19369165e-01,
        8.37352638e-01,  6.36671900e-01,  8.31862207e-01,  5.72923600e-01,
       -7.55236962e-01,  1.52224525e+00, -8.38499469e-01, -3.12951531e-01,
        9.84699585e-01, -1.89291000e-01, -7.21759805e-01,  1.78109327e+00,
       -5.14801249e-01,  1.33284925e+00, -1.56487893e-01, -1.64727748e+00,
        3.28888638e-01, -2.95063818e-01, -9.69732425e-02, -1.32757560e-01,
        1.61172309e+00, -3.29289958e-01,  4.65154364e-01,  1.02861679e-01,
        1.60105878e+00, -7.18349616e-01, -1.40939559e+00, -1.06518609e-01,
       -6.34291651e-01,  3.49511636e-01, -2.37734547e-01,  4.53663730e-01,
       -1.52903087e+00,  1.31836757e+00, -1.09522423e+00,  4.67749600e-02,
        1.13761148e+00,  2.84829155e+00, -4.35394321e-01,  1.32950422e+00,
        7.17454503e-01,  5.46790457e-01,  1.09113354e+00,  1.10290816e+00,
        6.15479665e-01, -8.97752928e-01,  2.37395940e+00, -1.86397871e+00,
        1.22659701e+00, -1.15206372e+00, -6.38693119e-01, -1.36639181e+00,
        9.54383146e-01, -1.83674211e+00, -6.36238637e-01,  3.46304096e-01,
        9.90738856e-01,  9.01186947e-01,  3.44262627e-01,  1.55741468e+00,
        9.18538593e-01,  4.01894532e-01, -1.95926070e-01, -7.08573490e-01,
        8.46695926e-01, -1.85961506e+00,  8.66061418e-01, -1.07155118e+00,
        5.70729494e-01,  2.53266449e+00,  9.35324843e-01,  7.48218759e-01,
       -9.83291373e-01, -7.84239797e-01, -8.95677005e-01, -3.46427255e-01,
       -1.29392721e+00,  1.31157744e+00,  3.82455990e-02, -1.49200276e+00,
        1.33217766e+00,  3.09434371e-01, -3.57669783e-01, -3.68676089e-01,
       -7.91682655e-01,  3.62309928e-01, -8.03294270e-02,  5.25187141e-01,
       -8.23426306e-01, -4.82515849e-01,  7.12728466e-01,  7.31586571e-01,
       -4.10193951e-01,  6.97619172e-01, -1.04975122e-01,  1.11700578e+00,
        1.14422647e+00, -9.88534799e-01,  8.45244390e-01,  1.03784526e+00,
       -7.48186051e-01, -1.48480797e+00, -5.74439479e-01,  6.55483043e-01,
        9.13659783e-01,  1.23815671e+00,  1.01092289e+00,  2.43981430e-02,
        1.24053868e+00, -7.14160294e-01,  6.42007957e-01,  2.10217676e-01,
        1.36856367e+00, -8.85855409e-01,  1.02206342e-02,  1.75097513e+00,
        8.01905212e-01,  4.07570938e-01, -1.26246873e+00, -9.60301970e-01,
       -1.77884108e+00,  5.58744419e-01, -1.23718577e+00, -3.45879542e-01,
       -1.92414849e+00, -6.66002677e-01, -8.89394861e-01,  9.96885256e-01,
        1.32071943e+00,  9.63246213e-01, -3.33964865e-01, -1.09281187e-01,
       -1.35168213e-02, -1.53428146e-01,  1.80633583e+00, -6.87494686e-02,
        4.56448681e-01,  8.38667103e-01,  3.84938139e-01, -1.81128061e-01,
        5.15659059e-01, -5.20134748e-01, -7.44672277e-01,  1.07605947e+00,
       -7.71565363e-01,  7.40559740e-01, -8.03443242e-01, -1.00998431e+00,
       -1.10342848e+00, -6.34103743e-01,  4.24439372e-01,  5.39685332e-01,
       -3.08617146e-01, -1.05749152e+00, -9.58144380e-01,  7.53905957e-02,
       -1.56008253e+00, -8.25073800e-01,  6.06727541e-01, -4.32392973e-01,
        8.89805067e-01,  9.93954149e-02, -8.73589025e-01, -8.91036042e-01,
       -1.51061498e+00,  2.51933312e-02, -1.11021999e-01, -1.28645057e+00,
       -8.40131077e-02,  3.41818291e-01, -1.28017955e+00,  1.20562988e+00,
       -1.45639665e+00, -1.59521263e+00,  4.19817293e-01,  6.13271684e-01,
       -7.54047695e-01, -1.90890466e+00,  1.47986267e+00, -1.54722084e-01,
       -6.83128865e-01, -5.25441371e-01, -5.11315983e-01, -9.11934749e-02,
        4.15327363e-01,  2.27114631e-01, -6.79102377e-01, -2.97907884e-01,
       -1.74452199e+00,  1.26121850e-01, -1.39722121e-01, -5.12258905e-01,
       -1.29123895e+00, -5.56527122e-01, -6.42037329e-01, -4.61760007e-01,
       -1.72192833e+00,  2.98464032e-01, -7.86578162e-01,  1.30388372e+00,
        7.54287045e-01, -8.14974358e-02,  7.31173879e-01,  1.00849166e+00,
        4.46223646e-02,  1.67482919e+00,  6.17764580e-01, -6.62242987e-02,
        7.73664541e-01,  8.92548019e-01,  2.61734686e-01, -4.90562013e-01,
       -5.90461406e-01, -4.73678101e-01, -3.51020088e-01,  1.18437660e+00,
        2.49670534e-01,  6.58917425e-02,  5.95162112e-01,  2.18048948e-01,
       -3.69857132e-01, -3.16417090e-01,  1.01122734e+00,  8.75677308e-01,
        1.17959248e+00, -2.61650833e-01,  7.34648323e-01, -9.00963609e-01,
        1.39037242e-01,  1.73787892e+00,  8.85153896e-01, -5.37609665e-01,
       -7.00546780e-01, -3.50878066e-01, -7.95136074e-02, -3.24070923e-01,
       -2.41472875e-01, -2.23701376e+00, -7.16693457e-01, -1.31208840e+00,
       -1.96033861e+00,  4.22958838e-01, -1.32075027e+00, -1.73523701e-02,
       -1.13638531e+00, -1.71448819e-02,  2.05588172e+00,  6.33687487e-02,
       -1.66627646e+00, -1.91996597e+00,  9.02367251e-01, -4.97353163e-01,
        1.01686848e+00,  1.13077937e+00,  2.00922924e+00, -3.55312109e-01,
        2.44025317e-01,  2.87861976e-01, -2.84181345e-01,  3.56705426e-01,
        1.31567982e-01, -1.08968725e+00, -1.81378090e-01, -1.03478004e+00,
       -4.63689908e-01, -1.63218082e+00,  5.45583652e-01,  8.50449679e-01,
        7.31891155e-01,  1.05275165e+00,  1.49304517e-01, -8.41450269e-01,
       -6.68946647e-01, -2.47549521e-01,  3.59004754e-02,  2.52865957e-01,
        5.25892725e-01,  1.20366020e+00, -7.30428883e-01, -5.98242154e-01,
        1.52188789e-01, -9.16784900e-01,  1.14582899e+00,  1.81147094e+00,
       -8.85461593e-01,  7.40697774e-01,  6.70447874e-01, -2.62265222e+00,
        4.12242993e-01, -1.05397173e-01,  2.85684157e-02,  6.03874484e-01,
       -2.42089511e+00,  2.86573933e-01,  1.79462173e+00,  9.40317364e-01,
       -3.33101495e-01, -1.06074724e+00,  5.30929566e-01,  5.93240673e-01,
        1.10745901e+00, -2.19538797e+00,  1.58517241e-01, -1.50376590e-01,
       -5.26890883e-01,  2.76966955e-01,  5.23944062e-01,  2.73989645e-01,
       -6.94205446e-01, -3.74942202e-01,  9.91527581e-01,  5.81235215e-01,
        1.60984635e+00, -1.05452689e+00, -1.51027261e+00,  4.20273978e-01,
        1.22170704e+00,  1.82964672e+00,  8.74468727e-01, -1.07203131e-01,
        1.03391205e+00, -1.50092260e-01, -7.15000177e-01,  5.86134200e-01,
       -1.63947822e+00, -1.02471945e+00, -7.80488232e-01,  7.39034131e-01,
       -1.58047442e+00, -5.59583954e-01,  6.02393734e-02,  2.22590965e-01,
       -1.30176603e-01,  2.44804668e+00,  6.64187610e-01,  2.22178173e-01,
       -1.37556482e-01, -1.38353909e+00, -1.11781581e+00,  1.12036003e-01,
       -5.25192354e-01, -4.70196172e-01, -1.60177522e+00, -1.59578824e+00,
        2.64387930e-01, -8.62155396e-02,  1.08697509e+00, -1.37732333e+00,
       -6.27122929e-01, -2.78633613e-01,  9.14837889e-01, -2.31763950e+00,
        9.53021175e-01,  4.32216550e-01, -9.01901783e-01, -1.00989667e+00,
        9.16166394e-01,  1.10113540e+00, -5.43055445e-01,  1.06458740e+00,
        3.63774311e-01, -6.09061973e-01,  1.99306845e+00,  6.02311267e-02,
        1.32340206e+00,  2.67404318e-01, -3.20281905e-01, -7.70787365e-01,
        3.06087004e-01, -4.31642418e-01,  7.05904336e-01,  4.19699245e-01,
        9.15553245e-02, -7.68067401e-01, -1.25111951e+00,  8.22906568e-01,
        2.19827688e+00, -9.66207877e-01, -6.04550388e-01, -4.42046800e-01,
        4.76383148e-01, -1.75521329e+00, -4.92915950e-01,  5.01325612e-01,
        2.94964262e-01, -3.30761841e-01, -8.57921035e-01, -1.02075066e+00,
        1.27274901e+00, -1.39738439e-01, -3.10038642e-01,  1.36085212e+00,
        8.12667862e-02, -4.14595215e-01,  4.22191539e-01, -2.79660771e-01,
        4.48448464e-01, -7.24301667e-02, -2.56343354e+00,  1.68568791e+00,
       -1.24618330e+00, -2.18886325e-01, -1.03101832e+00,  7.47055475e-01,
        4.65723276e-01, -5.85314131e-01,  1.43055598e-01, -9.05813783e-01,
        5.83991362e-02, -1.07433790e+00, -1.60701116e-01,  7.87753992e-01,
        1.18084371e+00, -2.62756304e-01, -4.97769411e-03,  1.99047991e-01,
       -1.02487234e+00, -1.23732328e+00,  1.03452089e+00,  3.06722517e-01,
        1.25838002e+00,  1.49893701e-02,  7.69047657e-01,  6.23989716e-01,
        6.34562695e-01, -4.20951655e-01,  2.58619323e-02,  2.11346667e+00,
        9.71363390e-02, -1.42116998e+00,  1.60525967e+00,  1.35466118e+00,
        2.74763445e-01, -9.97995078e-01, -6.59711859e-01,  3.22160182e-01,
       -2.92840903e-01, -5.96358868e-02,  8.10246811e-01, -5.74817270e-02,
        1.89480629e+00, -4.08118996e-01,  1.23260436e+00,  5.24948641e-01,
       -9.38917491e-01,  8.80041398e-01,  2.33649715e-01,  4.44346152e-01,
       -1.35464996e+00,  4.45946932e-01,  6.33463499e-01,  1.41505836e-01,
       -5.42956273e-01,  1.34438638e-01,  2.75989606e-02, -7.81385170e-01,
        8.72891923e-01, -4.31872815e-02,  1.31830503e+00, -1.11187768e+00,
        5.89626886e-01, -1.21110769e+00,  2.63107937e-01,  1.83606886e+00,
        1.82739058e+00, -6.78427701e-02, -1.72935563e+00,  1.03139447e+00])

In [99]:
quartiles = pd.qcut(data, 4, precision=2)

In [100]:
quartiles

[(0.72, 3.04], (0.72, 3.04], (0.72, 3.04], (-3.07, -0.68], (-0.68, 0.015], ..., (0.72, 3.04], (0.72, 3.04], (-0.68, 0.015], (-3.07, -0.68], (0.72, 3.04]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.07, -0.68] < (-0.68, 0.015] < (0.015, 0.72] < (0.72, 3.04]]

In [101]:
quartiles.value_counts()

(-3.07, -0.68]    250
(-0.68, 0.015]    250
(0.015, 0.72]     250
(0.72, 3.04]      250
Name: count, dtype: int64

In [103]:
pd.qcut(data, [0,0.1,0.5,0.9,1.]).value_counts()

(-3.061, -1.266]    100
(-1.266, 0.015]     400
(0.015, 1.227]      400
(1.227, 3.044]      100
Name: count, dtype: int64

In [129]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [130]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.013165    -0.003330    -0.029027    -0.003246
std       1.000244     1.028619     1.036234     1.018807
min      -3.045902    -3.036792    -3.539812    -3.431820
25%      -0.635658    -0.675157    -0.731774    -0.696379
50%       0.008555    -0.011320    -0.054595     0.007655
75%       0.705397     0.697579     0.644509     0.692253
max       2.970247     3.339163     3.430107     3.103216

In [131]:
col = data[2]

In [132]:
col[col.abs() >3]

30    -3.539812
137    3.256573
322    3.423561
327    3.430107
887   -3.102559
Name: 2, dtype: float64

In [133]:
col[abs(col) >3]

30    -3.539812
137    3.256573
322    3.423561
327    3.430107
887   -3.102559
Name: 2, dtype: float64

In [138]:
data[(data.abs() >3).any(axis = "columns")]

            0         1         2         3
27   0.487249 -0.881105  0.151498  3.103216
30  -1.011141 -1.566926 -3.539812 -0.827922
57  -0.501571  3.339163  1.183119  0.601517
137  0.697314 -1.535528  3.256573 -0.659504
199  0.093080 -3.036792  0.160421 -0.486872
274 -0.449165  1.072948  0.285085 -3.051679
322  1.126269  0.130638  3.423561  0.855699
327 -0.316325  0.179506  3.430107  1.165584
386 -0.634798 -0.170982  0.025356 -3.030925
559  1.099518  1.541485  0.396349 -3.431820
604 -3.045902 -0.099247  0.989297  0.941181
742 -0.373149 -0.640548  0.842787  3.075866
887  1.221903  0.028149 -3.102559  0.030605

In [139]:
data[(data.abs() >3).any(axis  = 'columns')]

            0         1         2         3
27   0.487249 -0.881105  0.151498  3.103216
30  -1.011141 -1.566926 -3.539812 -0.827922
57  -0.501571  3.339163  1.183119  0.601517
137  0.697314 -1.535528  3.256573 -0.659504
199  0.093080 -3.036792  0.160421 -0.486872
274 -0.449165  1.072948  0.285085 -3.051679
322  1.126269  0.130638  3.423561  0.855699
327 -0.316325  0.179506  3.430107  1.165584
386 -0.634798 -0.170982  0.025356 -3.030925
559  1.099518  1.541485  0.396349 -3.431820
604 -3.045902 -0.099247  0.989297  0.941181
742 -0.373149 -0.640548  0.842787  3.075866
887  1.221903  0.028149 -3.102559  0.030605

In [141]:
data[(data.abs() >3)] = np.sign(data) *3

In [142]:
data[data.abs() > 3]

      0   1   2   3
0   NaN NaN NaN NaN
1   NaN NaN NaN NaN
2   NaN NaN NaN NaN
3   NaN NaN NaN NaN
4   NaN NaN NaN NaN
..   ..  ..  ..  ..
995 NaN NaN NaN NaN
996 NaN NaN NaN NaN
997 NaN NaN NaN NaN
998 NaN NaN NaN NaN
999 NaN NaN NaN NaN

[1000 rows x 4 columns]

In [143]:

data[data.abs() > 3] = np.sign(data) * 3

In [144]:
data[data.abs() > 3]
data[data.abs() > 3] = np.sign(data) * 3

In [145]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.013211    -0.003633    -0.029495    -0.002911
std       1.000104     1.027463     1.030774     1.016660
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.635658    -0.675157    -0.731774    -0.696379
50%       0.008555    -0.011320    -0.054595     0.007655
75%       0.705397     0.697579     0.644509     0.692253
max       2.970247     3.000000     3.000000     3.000000

In [146]:
#perm and random sampling

In [147]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [148]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [149]:
sampler = np.random.permutation(5)

In [150]:
sampler

array([2, 4, 3, 1, 0])

In [151]:
df.take(sampler)

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [152]:
column_sampler = np.random.permutation(7)

In [153]:
column_sampler

array([0, 6, 4, 2, 3, 5, 1])

In [154]:
df.take(column_sampler, axis= "columns")

    0   6   4   2   3   5   1
0   0   6   4   2   3   5   1
1   7  13  11   9  10  12   8
2  14  20  18  16  17  19  15
3  21  27  25  23  24  26  22
4  28  34  32  30  31  33  29

In [155]:
df.sample( n =3)

    0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20

In [156]:
choices = pd.Series([5, 7, -1, 6, 4])

In [157]:
choices.sample(n =10, replace=True)

3    6
1    7
4    4
0    5
1    7
2   -1
1    7
2   -1
3    6
1    7
dtype: int64

In [159]:
#Computing Indicator/Dummy Variables

In [160]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
   .....:                    "data1": range(6)})

In [161]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [162]:
pd.get_dummies(df['key'], dtype= float)

     a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [163]:
dummies = pd.get_dummies(df['key'], prefix= 'key', dtype= float)

In [164]:
dummies

   key_a  key_b  key_c
0    0.0    1.0    0.0
1    0.0    1.0    0.0
2    1.0    0.0    0.0
3    0.0    0.0    1.0
4    1.0    0.0    0.0
5    0.0    1.0    0.0

In [171]:
df_with_dummy = df[['data1']].join(dummies)

In [172]:
df_with_dummy

   data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [173]:
val = "a,b,  guido"

In [174]:
val.split(',')

['a', 'b', '  guido']

In [175]:
pieces = [x.strip() for x in val.split(',')]

In [176]:
pieces

['a', 'b', 'guido']

In [177]:
first, second, third = pieces

In [178]:
first + '::' +  second + '::' + third

'a::b::guido'

In [179]:
'::'.join(pieces)

'a::b::guido'

In [180]:
"guido" in val

True

In [181]:
val

'a,b,  guido'

In [182]:
val.index(',')

1

In [183]:
val.find(':')

-1

In [184]:
val.index(":")

ValueError: substring not found

In [185]:
val.count(",")

2

In [186]:
val.replace(',', '::')

'a::b::  guido'

In [187]:
import re

In [188]:
text = "foo    bar\t baz  \tqux"

In [189]:
re.split(r'\s+', text)

['foo', 'bar', 'baz', 'qux']

In [192]:
regex = re.compile(r"\s+")

In [193]:
regex.findall(text)

['    ', '\t ', '  \t']

In [194]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

In [195]:
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [197]:
regex = re.compile(pattern, flags= re.IGNORECASE)

In [198]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [200]:
m = regex.search(text)

In [201]:
m

In [202]:
text[m.start():m.end()]

'dave@google.com'

In [203]:
regex.match(text)

In [205]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

In [206]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [207]:
regex = re.compile(pattern, flags=  re.IGNORECASE)

In [208]:
regex

re.compile(r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})',
           re.IGNORECASE|re.UNICODE)

In [209]:
m =regex.match("wesm@bright.net")

In [210]:
m

In [211]:
m.groups()

('wesm', 'bright', 'net')

In [213]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

In [214]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
   .....:         "Rob": "rob@gmail.com", "Wes": np.nan}

In [215]:
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [216]:
data = pd.Series(data)

In [217]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [218]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [219]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [220]:
data_as_string_ext = data.astype('string')

In [222]:
data_as_string_ext.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [223]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [237]:
data.str.findall(pattern,flags= re.IGNORECASE).str[0]

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [225]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [226]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [227]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [238]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [239]:
data.str.extract(pattern, flags= re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [240]:
values = pd.Series([0, 1, 0, 0] * 2)

In [241]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [242]:
dim = pd.Series(['apple', 'orange'])

In [243]:
dim

0     apple
1    orange
dtype: object

In [244]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [245]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [246]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [247]:
N = len(fruits)

In [248]:
rng = np.random.default_rng(seed =12345)

In [249]:
 df = pd.DataFrame({'fruit': fruits,
   .....:                    'basket_id': np.arange(N),
   .....:                    'count': rng.integers(3, 15, size=N),
   .....:                    'weight': rng.uniform(0, 4, size=N)},
   .....:                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [250]:
df

   basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [255]:
type(df['fruit'])

pandas.core.series.Series

In [252]:
fruits_cat = df['fruit'].astype('category')

In [253]:
fruits_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [257]:
c = fruits_cat.array

In [258]:
type(c)

pandas.core.arrays.categorical.Categorical

In [259]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [260]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [261]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [262]:
df['fruit'] = df['fruit'].astype('category')

In [263]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [264]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [265]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [267]:
categories = ['foo', 'bar', 'baz']

In [268]:
codes = [0, 1, 2, 0, 0, 1]

In [269]:
my_cat_2 = pd.Categorical.from_codes(codes, categories)

In [270]:
my_cat_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [272]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
   .....:                                         ordered=True)

In [273]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [274]:
my_cat_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [275]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)

In [276]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [279]:
bins = pd.qcut(draws, 4, labels= ['Q1', 'Q2', 'Q3', 'Q4'])

In [280]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [282]:
bins.codes[:5]

array([0, 3, 0, 1, 1], dtype=int8)

In [283]:
bins = pd.Series(bins, name= 'quartile')

In [284]:
bins

0      Q1
1      Q4
2      Q1
3      Q2
4      Q2
       ..
995    Q3
996    Q3
997    Q2
998    Q3
999    Q2
Name: quartile, Length: 1000, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [286]:
results = (
    pd.Series(draws)
    .groupby(bins, observed=False)
    .agg(['count', 'min', 'max'])
    .reset_index()
)

In [287]:
results

  quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [288]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [289]:
N = 1_000_000

In [290]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [291]:
labels

0         foo
1         bar
2         baz
3         qux
4         foo
         ...
999995    qux
999996    foo
999997    bar
999998    baz
999999    qux
Length: 1000000, dtype: object

In [292]:
categories = labels.astype('category')

In [293]:
labels.memory_usage(deep=True)

52000132

In [294]:
categories.memory_usage(deep = True)

1000512

In [295]:
%time _=labels.astype('category')

CPU times: user 33.8 ms, sys: 7.42 ms, total: 41.2 ms
Wall time: 38.3 ms

In [296]:
%timeit labels.value_counts()

15.3 ms ± 58.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [297]:
%timeit categories.value_counts()

1.41 ms ± 8.75 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [298]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [299]:
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [301]:
cat_s = s.astype('category')

In [302]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [305]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [306]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [307]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [308]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [309]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [310]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [311]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [312]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]

In [313]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [315]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [316]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [317]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [320]:
pd.get_dummies(cat_s, dtype= 'float')

     a    b    c    d
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0
7  0.0  0.0  0.0  1.0