In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"key1" : ["a", "a", None, "b", "b", "a", None],
   ....:                    "key2" : pd.Series([1, 2, 1, 2, 1, None, 1],
   ....:                                       dtype="Int64"),
   ....:                    "data1" : np.random.standard_normal(7),
   ....:                    "data2" : np.random.standard_normal(7)})

In [3]:
df

   key1  key2     data1     data2
0     a     1 -0.315563  0.538326
1     a     2 -0.357389  0.089108
2  None     1  0.067608 -1.733631
3     b     2  0.530566  2.099758
4     b     1  1.160737  0.352204
5     a  <NA>  0.873738  0.221463
6  None     1 -0.858392 -0.712527

In [4]:
grouped = df['data1'].groupby(df['key1'])

In [5]:
grouped

In [6]:
grouped.mean()

key1
a    0.066929
b    0.845652
Name: data1, dtype: float64

In [10]:
df['data1'].groupby([df['key1'], df['key2']]).mean().unstack()

key2         1         2
key1
a    -0.315563 -0.357389
b     1.160737  0.530566

In [11]:
states = np.array(["OH", "CA", "CA", "OH", "OH", "CA", "OH"])

In [12]:
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [14]:
df['data1'].groupby([states, years]).mean().unstack()

        2005      2006
CA  0.258174  0.067608
OH  0.107502  0.151173

In [16]:
df.groupby('key1').mean()

      key2     data1     data2
key1
a      1.5  0.066929  0.282966
b      1.5  0.845652  1.225981

In [18]:
df.groupby('key2').mean(numeric_only= True)

         data1     data2
key2
1     0.013598 -0.388907
2     0.086589  1.094433

In [20]:
df.groupby(['key1', 'key2']).mean().unstack()

         data1               data2
key2         1         2         1         2
key1
a    -0.315563 -0.357389  0.538326  0.089108
b     1.160737  0.530566  0.352204  2.099758

In [21]:
df.groupby(['key1', 'key2']).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [23]:
df.groupby('key1', dropna= False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [24]:
df.groupby(['key1', 'key2'], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [25]:
df.groupby('key1').count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

In [26]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1 -0.315563  0.538326
1    a     2 -0.357389  0.089108
5    a  <NA>  0.873738  0.221463
b
  key1  key2     data1     data2
3    b     2  0.530566  2.099758
4    b     1  1.160737  0.352204

In [27]:
for (k1,k2), group in df.groupby(['key1', 'key2']):
    print((k1,k2))
    print(group)

('a', np.int64(1))
  key1  key2     data1     data2
0    a     1 -0.315563  0.538326
('a', np.int64(2))
  key1  key2     data1     data2
1    a     2 -0.357389  0.089108
('b', np.int64(1))
  key1  key2     data1     data2
4    b     1  1.160737  0.352204
('b', np.int64(2))
  key1  key2     data1     data2
3    b     2  0.530566  2.099758

In [29]:
grouped = df.groupby(
    {
        'key1':'key',
        'key2':'key',
        'data1':'data',
        'data2':'data'
    },
    axis = 1
)

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_11167/517260041.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  grouped = df.groupby(

In [30]:
for group_key, group_values in grouped:
    print(group_key)
    print(group_values)

data
      data1     data2
0 -0.315563  0.538326
1 -0.357389  0.089108
2  0.067608 -1.733631
3  0.530566  2.099758
4  1.160737  0.352204
5  0.873738  0.221463
6 -0.858392 -0.712527
key
   key1  key2
0     a     1
1     a     2
2  None     1
3     b     2
4     b     1
5     a  <NA>
6  None     1

In [36]:
df.groupby("key1")["data2"]

In [40]:
df.groupby("key1")[["data2"]].mean()

         data2
key1
a     0.282966
b     1.225981

In [41]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),
   ....:                       columns=["a", "b", "c", "d", "e"],
   ....:                       index=["Joe", "Steve", "Wanda", "Jill", "Trey"])

In [42]:
people

              a         b         c         d         e
Joe   -0.589968 -0.290391 -0.738203 -2.518296  0.347669
Steve  0.182528  0.601925 -0.174747  0.405872  1.624348
Wanda  1.834095  1.306549 -0.275223 -1.425739  0.419070
Jill   0.004119  0.309899  1.577420  0.187903  0.937733
Trey  -1.216083 -1.961754 -0.584613  0.225931 -0.926272

In [43]:
people.iloc[2:3, [1, 2]] = np.nan

In [44]:
people

              a         b         c         d         e
Joe   -0.589968 -0.290391 -0.738203 -2.518296  0.347669
Steve  0.182528  0.601925 -0.174747  0.405872  1.624348
Wanda  1.834095       NaN       NaN -1.425739  0.419070
Jill   0.004119  0.309899  1.577420  0.187903  0.937733
Trey  -1.216083 -1.961754 -0.584613  0.225931 -0.926272

In [45]:
mapping = {"a": "red", "b": "red", "c": "blue",
   ....:            "d": "blue", "e": "red", "f" : "orange"}

In [46]:
mapping

{'a': 'red', 'b': 'red', 'c': 'blue', 'd': 'blue', 'e': 'red', 'f': 'orange'}

In [47]:
by_column = people.groupby(mapping, axis= 1)

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_11167/912099214.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  by_column = people.groupby(mapping, axis= 1)

In [49]:
by_column.sum()

           blue       red
Joe   -3.256499 -0.532691
Steve  0.231125  2.408801
Wanda -1.425739  2.253165
Jill   1.765323  1.251750
Trey  -0.358682 -4.104109

In [50]:
map_series = pd.Series(mapping)

In [51]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

In [54]:
people.groupby(map_series, axis= 1).count()

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_11167/413409095.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  people.groupby(map_series, axis= 1).count()

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

In [55]:
people

              a         b         c         d         e
Joe   -0.589968 -0.290391 -0.738203 -2.518296  0.347669
Steve  0.182528  0.601925 -0.174747  0.405872  1.624348
Wanda  1.834095       NaN       NaN -1.425739  0.419070
Jill   0.004119  0.309899  1.577420  0.187903  0.937733
Trey  -1.216083 -1.961754 -0.584613  0.225931 -0.926272

In [57]:
people.groupby(len).sum()

          a         b         c         d         e
3 -0.589968 -0.290391 -0.738203 -2.518296  0.347669
4 -1.211965 -1.651856  0.992808  0.413834  0.011461
5  2.016623  0.601925 -0.174747 -1.019867  2.043418

In [58]:
key_list = ["one", "one", "one", "two", "two"]

In [59]:
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one -0.589968 -0.290391 -0.738203 -2.518296  0.347669
4 two -1.216083 -1.961754 -0.584613  0.187903 -0.926272
5 one  0.182528  0.601925 -0.174747 -1.425739  0.419070

In [60]:
columns = pd.MultiIndex.from_arrays([["US", "US", "US", "JP", "JP"],
   ....:                                     [1, 3, 5, 1, 3]],
   ....:                                     names=["cty", "tenor"])

In [61]:
columns

MultiIndex([('US', 1),
            ('US', 3),
            ('US', 5),
            ('JP', 1),
            ('JP', 3)],
           names=['cty', 'tenor'])

In [63]:
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns=columns)

In [64]:
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0     -0.877868  1.383202  1.266109 -0.092901  0.037012
1     -1.004803  1.006586 -0.334556  1.345574 -0.070376
2      2.172265 -0.836718 -0.618131  0.097661 -0.761974
3     -0.090506 -0.452180  0.107330 -0.130431 -0.978523

In [65]:
hier_df.groupby(level= 'cty', axis= 1).count()

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_11167/1017776378.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_df.groupby(level= 'cty', axis= 1).count()

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

In [66]:
df

   key1  key2     data1     data2
0     a     1 -0.315563  0.538326
1     a     2 -0.357389  0.089108
2  None     1  0.067608 -1.733631
3     b     2  0.530566  2.099758
4     b     1  1.160737  0.352204
5     a  <NA>  0.873738  0.221463
6  None     1 -0.858392 -0.712527

In [67]:
grouped = df.groupby('key1')

In [68]:
grouped['data1'].nsmallest(2)

key1
a     1   -0.357389
      0   -0.315563
b     3    0.530566
      4    1.160737
Name: data1, dtype: float64

In [69]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [70]:
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  1.231127  0.449218
b        1  0.630171  1.747553

In [71]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0  0.066929  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0  0.845652  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a     0.279087  0.873738   3.0  0.282966  0.230838  0.089108  0.155286
b     1.003195  1.160737   2.0  1.225981  1.235707  0.352204  0.789093


           50%       75%       max
key1
a     0.221463  0.379895  0.538326
b     1.225981  1.662869  2.099758

[2 rows x 24 columns]

In [72]:
tips = pd.read_csv('../examples/tips.csv')

In [73]:
tips

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [74]:
tips["tip_pct"] = tips["tip"] / tips["total_bill"]

In [75]:
tips

     total_bill   tip smoker   day    time  size   tip_pct
0         16.99  1.01     No   Sun  Dinner     2  0.059447
1         10.34  1.66     No   Sun  Dinner     3  0.160542
2         21.01  3.50     No   Sun  Dinner     3  0.166587
3         23.68  3.31     No   Sun  Dinner     2  0.139780
4         24.59  3.61     No   Sun  Dinner     4  0.146808
..          ...   ...    ...   ...     ...   ...       ...
239       29.03  5.92     No   Sat  Dinner     3  0.203927
240       27.18  2.00    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75     No   Sat  Dinner     2  0.098204
243       18.78  3.00     No  Thur  Dinner     2  0.159744

[244 rows x 7 columns]

In [76]:
grouped = tips.groupby(['day', 'smoker'])

In [77]:
grouped_pct = grouped["tip_pct"]

In [80]:
grouped_pct.agg(['mean', 'std', peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [83]:
grouped_pct.agg([('average','mean'), ('stdev','std'), peak_to_peak])

              average     stdev  <function peak_to_peak at 0x162f13b00>
day  smoker
Fri  No      0.151650  0.028123                                0.067349
     Yes     0.174783  0.051293                                0.159925
Sat  No      0.158048  0.039767                                0.235193
     Yes     0.147906  0.061375                                0.290095
Sun  No      0.160113  0.042347                                0.193226
     Yes     0.187250  0.154134                                0.644685
Thur No      0.160298  0.038774                                0.193350
     Yes     0.163863  0.039389                                0.151240

In [84]:
functions = ["count", "mean", "max"]

In [86]:
result = grouped[['tip_pct', 'total_bill']].agg(functions)

In [87]:
result['tip_pct']

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [90]:
ftuples = [("Average", "mean"), ("Variance", "var")]

In [95]:
grouped[["tip_pct", "total_bill"]].agg(ftuples)

              tip_pct           total_bill
              Average  Variance    Average    Variance
day  smoker
Fri  No      0.151650  0.000791  18.420000   25.596333
     Yes     0.174783  0.002631  16.813333   82.562438
Sat  No      0.158048  0.001581  19.661778   79.908965
     Yes     0.147906  0.003767  21.276667  101.387535
Sun  No      0.160113  0.001793  20.506667   66.099980
     Yes     0.187250  0.023757  24.120000  109.046044
Thur No      0.160298  0.001503  17.113111   59.625081
     Yes     0.163863  0.001551  19.190588   69.808518

In [96]:
grouped.agg(
    {
        'tip': 'max',
        'size': 'sum'
    }
)

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [98]:
grouped.agg(
    {
        'tip_pct': ['min','max', 'mean','std'],
        'size': 'sum'
    }
)

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40

In [104]:
grouped = tips.groupby(["day", "smoker"], as_index= False)

In [107]:
grouped.mean(numeric_only= True)

    day smoker  total_bill       tip      size   tip_pct
0   Fri     No   18.420000  2.812500  2.250000  0.151650
1   Fri    Yes   16.813333  2.714000  2.066667  0.174783
2   Sat     No   19.661778  3.102889  2.555556  0.158048
3   Sat    Yes   21.276667  2.875476  2.476190  0.147906
4   Sun     No   20.506667  3.167895  2.929825  0.160113
5   Sun    Yes   24.120000  3.516842  2.578947  0.187250
6  Thur     No   17.113111  2.673778  2.488889  0.160298
7  Thur    Yes   19.190588  3.030000  2.352941  0.163863

In [108]:
def top(df, n =5, column = 'tip_pct'):
    return df.sort_values(column, ascending = False)[:n]

In [109]:
top(tips, n =6)

     total_bill   tip smoker  day    time  size   tip_pct
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
232       11.61  3.39     No  Sat  Dinner     2  0.291990
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525

In [113]:
tips.groupby(['smoker','day']).apply(top,n =1 , column = 'total_bill', include_groups= False)

                 total_bill    tip    time  size   tip_pct
smoker day
No     Fri  94        22.75   3.25  Dinner     2  0.142857
       Sat  212       48.33   9.00  Dinner     4  0.186220
       Sun  156       48.17   5.00  Dinner     6  0.103799
       Thur 142       41.19   5.00   Lunch     5  0.121389
Yes    Fri  95        40.17   4.73  Dinner     4  0.117750
       Sat  170       50.81  10.00  Dinner     3  0.196812
       Sun  182       45.35   3.50  Dinner     3  0.077178
       Thur 197       43.11   5.00   Lunch     4  0.115982

In [114]:
result = tips.groupby("smoker")["tip_pct"].describe()

In [115]:
result

,count,mean,std,min,25%,50%,75%,max
smoker,,,,,,,,
No,151.0,0.159328,0.039910,0.056797,0.136906,0.155625,0.185014,0.291990
Yes,93.0,0.163196,0.085119,0.035638,0.106771,0.153846,0.195059,0.710345

In [117]:
result.unstack('smoker')

       smoker
count  No        151.000000
       Yes        93.000000
mean   No          0.159328
       Yes         0.163196
std    No          0.039910
       Yes         0.085119
min    No          0.056797
       Yes         0.035638
25%    No          0.136906
       Yes         0.106771
50%    No          0.155625
       Yes         0.153846
75%    No          0.185014
       Yes         0.195059
max    No          0.291990
       Yes         0.710345
dtype: float64

In [118]:
tips.groupby('smoker', group_keys=False).apply(top,)

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_11167/1502793219.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby('smoker', group_keys=False).apply(top)

     total_bill   tip smoker   day    time  size   tip_pct
232       11.61  3.39     No   Sat  Dinner     2  0.291990
149        7.51  2.00     No  Thur   Lunch     2  0.266312
51        10.29  2.60     No   Sun  Dinner     2  0.252672
185       20.69  5.00     No   Sun  Dinner     5  0.241663
88        24.71  5.85     No  Thur   Lunch     2  0.236746
172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

In [119]:
frame = pd.DataFrame({"data1": np.random.standard_normal(1000),
   ....:                       "data2": np.random.standard_normal(1000)})

In [120]:
frame

        data1     data2
0    0.512132  0.752609
1   -1.683482 -1.050720
2   -1.386024 -2.094457
3   -0.572007 -0.707741
4   -0.680751 -0.896219
..        ...       ...
995  0.006935 -1.125795
996  0.568016  1.046584
997  1.207560 -0.870014
998 -0.746613 -1.728617
999 -1.082175 -0.324990

[1000 rows x 2 columns]

In [121]:
quantiles = pd.cut(frame['data1'], 4)

In [122]:
quantiles

0       (0.0777, 1.636]
1      (-3.045, -1.481]
2      (-1.481, 0.0777]
3      (-1.481, 0.0777]
4      (-1.481, 0.0777]
             ...
995    (-1.481, 0.0777]
996     (0.0777, 1.636]
997     (0.0777, 1.636]
998    (-1.481, 0.0777]
999    (-1.481, 0.0777]
Name: data1, Length: 1000, dtype: category
Categories (4, interval[float64, right]): [(-3.045, -1.481] < (-1.481, 0.0777] < (0.0777, 1.636] < (1.636, 3.194]]

In [124]:
grouped = frame.groupby(quantiles)

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_11167/3439051546.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = frame.groupby(quantiles)

In [126]:
def gt_stats(group):
    return pd.DataFrame(
        {
            'min':group.min(),
            'max':group.max(),
            'count':group.count(),
            'mean': group.mean()
        }
    )

In [127]:
grouped.apply(gt_stats)

                             min       max  count      mean
data1
(-3.045, -1.481] data1 -3.039087 -1.483556     77 -1.906435
                 data2 -2.049979  3.047021     77  0.011155
(-1.481, 0.0777] data1 -1.475093  0.074511    482 -0.587835
                 data2 -2.897578  2.684552    482 -0.081346
(0.0777, 1.636]  data1  0.081732  1.621690    385  0.694199
                 data2 -3.001600  3.281839    385 -0.014469
(1.636, 3.194]   data1  1.646559  3.194419     56  2.106486
                 data2 -1.955187  1.831373     56  0.026608

In [128]:
 grouped.agg(["min", "max", "count", "mean"])

                     data1                               data2            \
                       min       max count      mean       min       max
data1
(-3.045, -1.481] -3.039087 -1.483556    77 -1.906435 -2.049979  3.047021
(-1.481, 0.0777] -1.475093  0.074511   482 -0.587835 -2.897578  2.684552
(0.0777, 1.636]   0.081732  1.621690   385  0.694199 -3.001600  3.281839
(1.636, 3.194]    1.646559  3.194419    56  2.106486 -1.955187  1.831373


                 count      mean
data1
(-3.045, -1.481]    77  0.011155
(-1.481, 0.0777]   482 -0.081346
(0.0777, 1.636]    385 -0.014469
(1.636, 3.194]      56  0.026608

In [135]:
quartiles_samp = pd.qcut(frame['data1'], 4, labels= False)

In [136]:
quartiles_samp

0      2
1      0
2      0
3      1
4      1
      ..
995    2
996    2
997    3
998    0
999    0
Name: data1, Length: 1000, dtype: int64

In [137]:
grouped = frame.groupby(quartiles_samp)

In [139]:
grouped.apply(gt_stats)

                  min       max  count      mean
data1
0     data1 -3.039087 -0.731852    250 -1.318659
      data2 -2.897578  3.047021    250 -0.012473
1     data1 -0.729574 -0.049003    250 -0.405912
      data2 -2.599485  2.684552    250 -0.143900
2     data1 -0.048362  0.616512    250  0.270144
      data2 -3.001600  2.282391    250 -0.086111
3     data1  0.619051  3.194419    250  1.274817
      data2 -2.794031  3.281839    250  0.072763

In [140]:
s = pd.Series(np.random.standard_normal(6))

In [141]:
s[::2] = np.nan

In [142]:
s

0         NaN
1    0.509765
2         NaN
3   -0.843740
4         NaN
5    0.804022
dtype: float64

In [143]:
s.fillna(s.mean())

0    0.156682
1    0.509765
2    0.156682
3   -0.843740
4    0.156682
5    0.804022
dtype: float64

In [144]:
states = ["Ohio", "New York", "Vermont", "Florida",
   .....:           "Oregon", "Nevada", "California", "Idaho"]

In [145]:
states

['Ohio',
 'New York',
 'Vermont',
 'Florida',
 'Oregon',
 'Nevada',
 'California',
 'Idaho']

In [146]:
group_key = ["East", "East", "East", "East",
   .....:              "West", "West", "West", "West"]

In [147]:
group_key

['East', 'East', 'East', 'East', 'West', 'West', 'West', 'West']

In [148]:
data = pd.Series(np.random.standard_normal(8), index=states)
data

Ohio          0.259938
New York      0.003846
Vermont      -0.014813
Florida      -0.060410
Oregon       -2.028064
Nevada        1.317143
California   -0.020856
Idaho        -0.925028
dtype: float64

In [149]:
data[["Vermont", "Nevada", "Idaho"]] = np.nan

In [150]:
data

Ohio          0.259938
New York      0.003846
Vermont            NaN
Florida      -0.060410
Oregon       -2.028064
Nevada             NaN
California   -0.020856
Idaho              NaN
dtype: float64

In [154]:
data.groupby(group_key).size()

East    4
West    4
dtype: int64

In [155]:
def fill_mean(group):
    return group.fillna(group.mean())

In [156]:
data.groupby(group_key).apply(fill_mean)

East  Ohio          0.259938
      New York      0.003846
      Vermont       0.067791
      Florida      -0.060410
West  Oregon       -2.028064
      Nevada       -1.024460
      California   -0.020856
      Idaho        -1.024460
dtype: float64

In [157]:
fill_values = {"East": 0.5, "West": -1}

In [158]:
fill_values

{'East': 0.5, 'West': -1}

In [160]:
def fill_func(group):
    return group.fillna(fill_values[group.name])

In [161]:
data.groupby(group_key).apply(fill_func)

East  Ohio          0.259938
      New York      0.003846
      Vermont       0.500000
      Florida      -0.060410
West  Oregon       -2.028064
      Nevada       -1.000000
      California   -0.020856
      Idaho        -1.000000
dtype: float64

In [162]:
#random sampling and permutation

In [163]:
suits = ["H", "S", "C", "D"]  # Hearts, Spades, Clubs, Diamonds
card_val = (list(range(1, 11)) + [10] * 3) * 4
base_names = ["A"] + list(range(2, 11)) + ["J", "K", "Q"]
cards = []
for suit in suits:
    cards.extend(str(num) + suit for num in base_names)

deck = pd.Series(card_val, index=cards)

In [164]:
deck

AH      1
2H      2
3H      3
4H      4
5H      5
6H      6
7H      7
8H      8
9H      9
10H    10
JH     10
KH     10
QH     10
AS      1
2S      2
3S      3
4S      4
5S      5
6S      6
7S      7
8S      8
9S      9
10S    10
JS     10
KS     10
QS     10
AC      1
2C      2
3C      3
4C      4
5C      5
6C      6
7C      7
8C      8
9C      9
10C    10
JC     10
KC     10
QC     10
AD      1
2D      2
3D      3
4D      4
5D      5
6D      6
7D      7
8D      8
9D      9
10D    10
JD     10
KD     10
QD     10
dtype: int64

In [165]:
def draw(deck, n = 5):
    return deck.sample(n)

In [166]:
draw(deck)

JS    10
8H     8
QD    10
7H     7
2S     2
dtype: int64

In [167]:
def get_suit(card):
    return card[-1]

In [169]:
deck.groupby(get_suit, group_keys= False).apply(draw, n =2)

KC    10
7C     7
3D     3
9D     9
4H     4
2H     2
5S     5
2S     2
dtype: int64

In [172]:
#group weighted average and correlation
df = pd.DataFrame({"category": ["a", "a", "a", "a","b", "b", "b", "b"],"data": np.random.standard_normal(8), "weights": np.random.uniform(size=8)})

In [174]:
df

  category      data   weights
0        a -0.204047  0.860125
1        a  0.075526  0.918608
2        a  0.661349  0.636236
3        a  0.008376  0.421178
4        b -1.920607  0.927564
5        b -0.762461  0.318730
6        b  1.269824  0.976872
7        b  0.233334  0.211336

In [175]:
grouped = df.groupby("category")

In [176]:
def get_wavg(group):
    return np.average(group["data"], weights=group["weights"])

In [177]:
grouped.apply(get_wavg)

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_11167/4286695940.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped.apply(get_wavg)

category
a    0.112185
b   -0.301802
dtype: float64

In [178]:
close_px = pd.read_csv("../examples/stock_px.csv", parse_dates= True, index_col= 0)

In [180]:
close_px.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2214 entries, 2003-01-02 to 2011-10-14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2214 non-null   float64
 1   MSFT    2214 non-null   float64
 2   XOM     2214 non-null   float64
 3   SPX     2214 non-null   float64
dtypes: float64(4)
memory usage: 86.5 KB

In [181]:
 close_px.tail(4)

              AAPL   MSFT    XOM      SPX
2011-10-11  400.29  27.00  76.27  1195.54
2011-10-12  402.19  26.96  77.16  1207.25
2011-10-13  408.43  27.18  76.37  1203.66
2011-10-14  422.00  27.27  78.11  1224.58

In [182]:
def spx_corr(group):
    return group.corrwith(group['SPX'])

In [184]:
rets = close_px.pct_change().dropna()

In [185]:
rets

                AAPL      MSFT       XOM       SPX
2003-01-03  0.006757  0.001421  0.000684 -0.000484
2003-01-06  0.000000  0.017975  0.024624  0.022474
2003-01-07 -0.002685  0.019052 -0.033712 -0.006545
2003-01-08 -0.020188 -0.028272 -0.004145 -0.014086
2003-01-09  0.008242  0.029094  0.021159  0.019386
...              ...       ...       ...       ...
2011-10-10  0.051406  0.026286  0.036977  0.034125
2011-10-11  0.029526  0.002227 -0.000131  0.000544
2011-10-12  0.004747 -0.001481  0.011669  0.009795
2011-10-13  0.015515  0.008160 -0.010238 -0.002974
2011-10-14  0.033225  0.003311  0.022784  0.017380

[2213 rows x 4 columns]

In [186]:
def get_year(x):
    return x.year

In [187]:
by_year = rets.groupby(get_year)

In [188]:
by_year.apply(spx_corr)

          AAPL      MSFT       XOM  SPX
2003  0.541124  0.745174  0.661265  1.0
2004  0.374283  0.588531  0.557742  1.0
2005  0.467540  0.562374  0.631010  1.0
2006  0.428267  0.406126  0.518514  1.0
2007  0.508118  0.658770  0.786264  1.0
2008  0.681434  0.804626  0.828303  1.0
2009  0.707103  0.654902  0.797921  1.0
2010  0.710105  0.730118  0.839057  1.0
2011  0.691931  0.800996  0.859975  1.0

In [189]:
def corr_appl_msft(group):
    return group['AAPL'].corr(group['MSFT'])

In [190]:
by_year.apply(corr_appl_msft)

2003    0.480868
2004    0.259024
2005    0.300093
2006    0.161735
2007    0.417738
2008    0.611901
2009    0.432738
2010    0.571946
2011    0.581987
dtype: float64

In [191]:
#Group-Wise Linear Regression

In [193]:
import statsmodels.api as sm

In [194]:
def regress(data, yvar = None, xvar = None):
    Y = data[yvar]
    X = data[xvar]
    X['intercept'] = 1.
    result = sm.OLS(Y, X).fit()
    return result.params

In [196]:
by_year.apply(regress, yvar = 'AAPL', xvar = ['SPX'])

           SPX  intercept
2003  1.195406   0.000710
2004  1.363463   0.004201
2005  1.766415   0.003246
2006  1.645496   0.000080
2007  1.198761   0.003438
2008  0.968016  -0.001110
2009  0.879103   0.002954
2010  1.052608   0.001261
2011  0.806605   0.001514

In [197]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,
   .....:                    'value': np.arange(12.)})

In [198]:
df

   key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [201]:
g = df.groupby('key')['value']

In [202]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [203]:
def get_mean(group):
    return group.mean()

In [204]:
g.transform(get_mean)

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [205]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [206]:
def times_two(group):
    return group*2

In [207]:
g.transform(times_two)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [208]:
def get_ranks(group):
    return group.rank(ascending = False)

In [209]:
g.transform(get_ranks)

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [210]:
def normalize(x):
    return (x - x.mean())/x.std()

In [211]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [213]:
g.apply(normalize)

   key  level_1     value
0    a        0 -1.161895
1    a        3 -0.387298
2    a        6  0.387298
3    a        9  1.161895
4    b        1 -1.161895
5    b        4 -0.387298
6    b        7  0.387298
7    b       10  1.161895
8    c        2 -1.161895
9    c        5 -0.387298
10   c        8  0.387298
11   c       11  1.161895

In [214]:
(df['value'] - g.transform('mean'))/g.transform('std')

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [215]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [217]:
tips.pivot_table(index= ['day', 'smoker'],
                values= ['size','tip','tip_pct','total_bill'])

                 size       tip   tip_pct  total_bill
day  smoker
Fri  No      2.250000  2.812500  0.151650   18.420000
     Yes     2.066667  2.714000  0.174783   16.813333
Sat  No      2.555556  3.102889  0.158048   19.661778
     Yes     2.476190  2.875476  0.147906   21.276667
Sun  No      2.929825  3.167895  0.160113   20.506667
     Yes     2.578947  3.516842  0.187250   24.120000
Thur No      2.488889  2.673778  0.160298   17.113111
     Yes     2.352941  3.030000  0.163863   19.190588

In [222]:
tips.pivot_table(index= ['time','day'], columns = 'smoker',
                values= ['tip_pct', 'size'], margins=True,
                aggfunc= len, fill_value = 0)
#"count" will exclude null values from the count within data groups, while len will not

            size          tip_pct
smoker        No Yes  All      No Yes  All
time   day
Dinner Fri     3   9   12       3   9   12
       Sat    45  42   87      45  42   87
       Sun    57  19   76      57  19   76
       Thur    1   0    1       1   0    1
Lunch  Fri     1   6    7       1   6    7
       Thur   44  17   61      44  17   61
All          151  93  244     151  93  244

In [ ]:
#crosstab

In [255]:
import pandas as pd
from io import StringIO

text = """Sample  Nationality  Handedness
1   USA  Right-handed
2   Japan    Left-handed
3   USA  Right-handed
4   Japan    Right-handed
5   Japan    Left-handed
6   Japan    Right-handed
7   USA  Right-handed
8   USA  Left-handed
9   Japan    Right-handed
10  USA  Right-handed"""

# Now use `text` instead of `data`
data = pd.read_table(StringIO(text), sep=r"\s+")
print(data)

   Sample Nationality    Handedness
0       1         USA  Right-handed
1       2       Japan   Left-handed
2       3         USA  Right-handed
3       4       Japan  Right-handed
4       5       Japan   Left-handed
5       6       Japan  Right-handed
6       7         USA  Right-handed
7       8         USA   Left-handed
8       9       Japan  Right-handed
9      10         USA  Right-handed

In [256]:
data

   Sample Nationality    Handedness
0       1         USA  Right-handed
1       2       Japan   Left-handed
2       3         USA  Right-handed
3       4       Japan  Right-handed
4       5       Japan   Left-handed
5       6       Japan  Right-handed
6       7         USA  Right-handed
7       8         USA   Left-handed
8       9       Japan  Right-handed
9      10         USA  Right-handed

In [258]:
pd.crosstab(data['Nationality'], data['Handedness'], margins = True)

Handedness   Left-handed  Right-handed  All
Nationality
Japan                  2             3    5
USA                    1             4    5
All                    3             7   10

In [262]:
pd.crosstab([tips["time"], tips["day"]], tips["smoker"], margins=True)

smoker        No  Yes  All
time   day
Dinner Fri     3    9   12
       Sat    45   42   87
       Sun    57   19   76
       Thur    1    0    1
Lunch  Fri     1    6    7
       Thur   44   17   61
All          151   93  244