In [4]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [5]:
#series
obj = pd.Series([4,7,-5,3])

In [6]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4,7,-5,3], index= ["d","b","a","c"])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2["c"]

np.int64(3)

In [13]:
obj2[["a", "b", "c"]]

a   -5
b    7
c    3
dtype: int64

In [14]:
obj2[obj2 >0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2 *2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [18]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [19]:
obj3 = pd.Series(sdata)

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [22]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index= states)

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj4.name = "population"

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj4.index.name = "state"

In [34]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
#data frame

In [36]:
#from dict to data frame
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [37]:
frame = pd.DataFrame(data)

In [38]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [39]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [40]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [41]:
pd.DataFrame(data, columns= ["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [42]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [43]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [44]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [45]:
frame2.index

RangeIndex(start=0, stop=6, step=1)

In [46]:
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [47]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [48]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [49]:
frame2["year"]

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [53]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [54]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [56]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [57]:
frame2["debt"] = 16.5

In [58]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [59]:
frame2["debt"] = np.arange(6.)

In [60]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [61]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])

In [62]:
val

2   -1.2
4   -1.5
5   -1.7
dtype: float64

In [63]:
frame2['debt'] = val

In [64]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [65]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [66]:
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False

In [67]:
del frame2['eastern']

In [69]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [71]:
In [72]: populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
   ....:                "Nevada": {2001: 2.4, 2002: 2.9}}

In [72]:
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [73]:
frame3 = pd.DataFrame(populations)

In [74]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [75]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [76]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [77]:
pdata = {
    "Ohio": frame3['Ohio'][:-1],
    "Nevada": frame3['Nevada'][:2],
}

In [78]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64,
 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [79]:
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [80]:
frame3.index.name = "year"

In [81]:
frame3

      Ohio  Nevada
year
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [82]:
frame3.columns.name = "state"

In [83]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [84]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [85]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [86]:
frame3.shape

(3, 2)

In [87]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [88]:
frame3.index

Index([2000, 2001, 2002], dtype='int64', name='year')

In [89]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [93]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

In [94]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [95]:
obj

a    0
b    1
c    2
dtype: int64

In [96]:
index = obj.index

In [97]:
index

Index(['a', 'b', 'c'], dtype='object')

In [98]:
index[1:]

Index(['b', 'c'], dtype='object')

In [99]:
labels = pd.Index(np.arange(3))

In [100]:
labels

Index([0, 1, 2], dtype='int64')

In [101]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [102]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [104]:
obj2.index is labels

True

In [106]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [107]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [108]:
obj.reindex(["a", "b", "c", "d", "e"])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [110]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [111]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [112]:
obj3.reindex(np.arange(6), method= "ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [113]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
   .....:                      index=["a", "c", "d"],
   .....:                      columns=["Ohio", "Texas", "California"])

In [114]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [116]:
frame2 = frame.reindex(index = ["a", "b","c", "d"])

In [117]:
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [118]:
states = ["Texas", "Utah", "California"]

In [119]:
frame.reindex(columns = states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [120]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [122]:
frame.loc[["a", "d", "c"], ["California","Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

In [123]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [124]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [125]:
new_obj = obj.drop("c")

In [126]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [127]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [128]:
 obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [130]:
obj1[[0,1,2]]

0    2
1    3
2    1
dtype: int64

In [131]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
   .....:                     index=["Ohio", "Colorado", "Utah", "New York"],
   .....:                     columns=["one", "two", "three", "four"])

In [132]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [134]:
data[["two", "three"]]

          two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [137]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [138]:
data[data["three"] >5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [139]:
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [140]:
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [141]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [142]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [144]:
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

In [146]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [147]:
 data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    4    5
Utah        11    8    9

In [148]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [150]:
data.loc[:"Utah", "two"]

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [152]:
data.iloc[:, :3][data.three>5]

          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [154]:
data.loc[data.three>2]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [155]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

In [156]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [157]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
   .....:                index=["a", "c", "e", "f", "g"])

In [158]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [159]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [160]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
   .....:                    columns=list("abcd"))

In [161]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [162]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
   .....:                    columns=list("abcde"))

In [163]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [165]:
df2.loc[1, "b"] = np.nan

In [166]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [167]:
df1.add(df2, fill_value= 0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [168]:
 frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
   .....:                      columns=list("bde"),
   .....:                      index=["Utah", "Ohio", "Texas", "Oregon"])

In [169]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [170]:
series = frame.iloc[0]

In [171]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [172]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [173]:
 series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [174]:
series2

b    0
e    1
f    2
dtype: int64

In [175]:
frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [176]:
series3 = frame["d"]

In [177]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [178]:
frame.sub(series3, axis= "index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [187]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
   .....:                      columns=list("bde"),
   .....:                      index=["Utah", "Ohio", "Texas", "Oregon"])

In [188]:
frame

               b         d         e
Utah    0.179145 -1.067657 -0.306744
Ohio   -3.026374  0.446232  0.322501
Texas   0.689102 -0.124734  1.042113
Oregon  1.619004  0.711841  2.139747

In [189]:
np.abs(frame)

               b         d         e
Utah    0.179145  1.067657  0.306744
Ohio    3.026374  0.446232  0.322501
Texas   0.689102  0.124734  1.042113
Oregon  1.619004  0.711841  2.139747

In [190]:
def f1(x):
    return x.max()- x.min()

In [191]:
frame.apply(f1)

b    4.645378
d    1.779498
e    2.446491
dtype: float64

In [192]:
frame.apply(f1, axis="columns")

Utah      1.246802
Ohio      3.472606
Texas     1.166846
Oregon    1.427905
dtype: float64

In [193]:
def f2(x):
    return pd.Series([x.min(), x.max()], index = ["min", "max"])

In [194]:
frame.apply(f2)

            b         d         e
min -3.026374 -1.067657 -0.306744
max  1.619004  0.711841  2.139747

In [195]:
def my_format(x):
    return f"{x:.2f}"

In [197]:
frame.map(my_format)

            b      d      e
Utah     0.18  -1.07  -0.31
Ohio    -3.03   0.45   0.32
Texas    0.69  -0.12   1.04
Oregon   1.62   0.71   2.14

In [198]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [199]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [200]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [201]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
   .....:                      index=["three", "one"],
   .....:                      columns=["d", "a", "b", "c"])

In [202]:
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [204]:
frame.sort_index(axis= "columns")

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [205]:
frame.sort_index(axis= "columns", ascending= False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [206]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [207]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [209]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [210]:
obj.sort_values(na_position= "first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [211]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [213]:
frame.sort_values("b", ascending=False)

   b  a
1  7  1
0  4  0
3  2  1
2 -3  0

In [215]:
frame.sort_values(["b", "a"])

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [216]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [217]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [218]:
obj.rank(method= "first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [219]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [220]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [221]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [222]:
obj.index.is_unique

False

In [223]:
obj["a"]

a    0
a    1
dtype: int64

In [224]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
   .....:                    [np.nan, np.nan], [0.75, -1.3]],
   .....:                   index=["a", "b", "c", "d"],
   .....:                   columns=["one", "two"])

In [225]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [226]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [227]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [228]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [229]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [230]:
#corr and covar
price = pd.read_pickle("../examples/yahoo_price.pkl")

In [231]:
volume = pd.read_pickle("../examples/yahoo_volume.pkl")

In [232]:
price

                  AAPL        GOOG         IBM       MSFT
Date
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
...                ...         ...         ...        ...
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [233]:
volume

                 AAPL      GOOG       IBM      MSFT
Date
2010-01-04  123432400   3927000   6155300  38409100
2010-01-05  150476200   6031900   6841400  49749600
2010-01-06  138040000   7987100   5605300  58182400
2010-01-07  119282800  12876600   5840600  50559700
2010-01-08  111902700   9483900   4197200  51197400
...               ...       ...       ...       ...
2016-10-17   23624900   1089500   5890400  23830000
2016-10-18   24553500   1995600  12770600  19149500
2016-10-19   20034600    116600   4632900  22878400
2016-10-20   24125800   1734200   4023100  49455600
2016-10-21   22384800   1260500   4401900  79974200

[1714 rows x 4 columns]

In [234]:
returns = price.pct_change()

In [235]:
returns

                AAPL      GOOG       IBM      MSFT
Date
2010-01-04       NaN       NaN       NaN       NaN
2010-01-05  0.001729 -0.004404 -0.012080  0.000323
2010-01-06 -0.015906 -0.025209 -0.006496 -0.006137
2010-01-07 -0.001849 -0.023280 -0.003462 -0.010400
2010-01-08  0.006648  0.013331  0.010035  0.006897
...              ...       ...       ...       ...
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

[1714 rows x 4 columns]

In [236]:
returns['MSFT'].corr(returns['IBM'])

np.float64(0.4997636114415114)

In [240]:
returns.corr().iloc[:,3]

AAPL    0.389695
GOOG    0.465919
IBM     0.499764
MSFT    1.000000
Name: MSFT, dtype: float64

In [238]:
returns.cov()

          AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [241]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [243]:
In [289]: obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [244]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [248]:
obj.value_counts( sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_3340/4037610489.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy())

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [249]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [250]:
mask = obj.isin(["b", "c"])

In [251]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [252]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [253]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])

In [254]:
unique_vals = pd.Series(["c", "b", "a"])

In [257]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [258]:
indices

array([0, 2, 1, 1, 0, 2])

In [259]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
   .....:                      "Qu2": [2, 3, 1, 2, 3],
   .....:                      "Qu3": [1, 5, 2, 4, 4]})

In [263]:
data['Qu1'].value_counts().sort_index(ascending=False)

Qu1
4    2
3    2
1    1
Name: count, dtype: int64

In [272]:
data.apply(pd.value_counts).fillna(0)

/var/folders/hv/s9l39pxx4s3_n1j2_7h7mm0c0000gn/T/ipykernel_3340/2493099384.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  data.apply(pd.value_counts).fillna(0)

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [273]:
data.apply(lambda col: col.value_counts()).fillna(0)

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [274]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})

In [275]:
data

   a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [276]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64