In [1]:
import numpy as np
import pandas as pd

In [3]:
#movieLens 1M dataset

In [4]:
unames = ['user_id', 'gender', 'age', 'occupation', 'zip']
users = pd.read_table('../datasets/movielens/users.dat', sep='::', header=None, names=unames, engine='python')

In [ ]:
rnames = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table('../datasets/movielens/ratings.dat', sep='::', header=None, names=rnames, engine='python')

In [6]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('../datasets/movielens/movies.dat', sep='::', header=None, names=mnames, engine='python')

In [7]:
users.head()

   user_id gender  age  occupation    zip
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455

In [8]:
data = pd.merge(pd.merge(ratings, users), movies)

In [10]:
data.iloc[0]

user_id                                            1
movie_id                                        1193
rating                                             5
timestamp                                  978300760
gender                                             F
age                                                1
occupation                                        10
zip                                            48067
title         One Flew Over the Cuckoo's Nest (1975)
genres                                         Drama
Name: 0, dtype: object

In [11]:
mean_ratings = data.pivot_table('rating', index = 'title', columns= 'gender', aggfunc= 'mean')

In [12]:
mean_ratings

gender                                             F         M
title
$1,000,000 Duck (1971)                      3.375000  2.761905
'Night Mother (1986)                        3.388889  3.352941
'Til There Was You (1997)                   2.675676  2.733333
'burbs, The (1989)                          2.793478  2.962085
...And Justice for All (1979)               3.828571  3.689024
...                                              ...       ...
Zed & Two Noughts, A (1985)                 3.500000  3.380952
Zero Effect (1998)                          3.864407  3.723140
Zero Kelvin (Kjærlighetens kjøtere) (1995)       NaN  3.500000
Zeus and Roxanne (1997)                     2.777778  2.357143
eXistenZ (1999)                             3.098592  3.289086

[3706 rows x 2 columns]

In [13]:
ratings_title = data.groupby('title').size()

In [14]:
ratings_title

title
$1,000,000 Duck (1971)                         37
'Night Mother (1986)                           70
'Til There Was You (1997)                      52
'burbs, The (1989)                            303
...And Justice for All (1979)                 199
                                             ...
Zed & Two Noughts, A (1985)                    29
Zero Effect (1998)                            301
Zero Kelvin (Kjærlighetens kjøtere) (1995)      2
Zeus and Roxanne (1997)                        23
eXistenZ (1999)                               410
Length: 3706, dtype: int64

In [15]:
active_titles = ratings_title.index[ratings_title >= 250]

In [16]:
active_titles

Index([''burbs, The (1989)', '10 Things I Hate About You (1999)',
       '101 Dalmatians (1961)', '101 Dalmatians (1996)', '12 Angry Men (1957)',
       '13th Warrior, The (1999)', '2 Days in the Valley (1996)',
       '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)',
       '2010 (1984)',
       ...
       'X-Men (2000)', 'Year of Living Dangerously (1982)',
       'Yellow Submarine (1968)', 'You've Got Mail (1998)',
       'Young Frankenstein (1974)', 'Young Guns (1988)',
       'Young Guns II (1990)', 'Young Sherlock Holmes (1985)',
       'Zero Effect (1998)', 'eXistenZ (1999)'],
      dtype='object', name='title', length=1216)

In [ ]:
mean_ratings = mean_ratings.loc[active_titles]

In [19]:
mean_ratings

gender                                    F         M
title
'burbs, The (1989)                 2.793478  2.962085
10 Things I Hate About You (1999)  3.646552  3.311966
101 Dalmatians (1961)              3.791444  3.500000
101 Dalmatians (1996)              3.240000  2.911215
12 Angry Men (1957)                4.184397  4.328421
...                                     ...       ...
Young Guns (1988)                  3.371795  3.425620
Young Guns II (1990)               2.934783  2.904025
Young Sherlock Holmes (1985)       3.514706  3.363344
Zero Effect (1998)                 3.864407  3.723140
eXistenZ (1999)                    3.098592  3.289086

[1216 rows x 2 columns]

In [20]:
top_female_ratings = mean_ratings.sort_values(by='F', ascending=False)

In [21]:
top_female_ratings

gender                                                     F         M
title
Close Shave, A (1995)                               4.644444  4.473795
Wrong Trousers, The (1993)                          4.588235  4.478261
Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)       4.572650  4.464589
Wallace & Gromit: The Best of Aardman Animation...  4.563107  4.385075
Schindler's List (1993)                             4.562602  4.491415
...                                                      ...       ...
Avengers, The (1998)                                1.915254  2.017467
Speed 2: Cruise Control (1997)                      1.906667  1.863014
Rocky V (1990)                                      1.878788  2.132780
Barb Wire (1996)                                    1.585366  2.100386
Battlefield Earth (2000)                            1.574468  1.616949

[1216 rows x 2 columns]

In [22]:
#measuring rating disagreement
mean_ratings['diff'] = mean_ratings['M'] - mean_ratings['F']

In [23]:
sorted_by_diff = mean_ratings.sort_values(by='diff')

In [24]:
sorted_by_diff

gender                                         F         M      diff
title
Dirty Dancing (1987)                    3.790378  2.959596 -0.830782
Jumpin' Jack Flash (1986)               3.254717  2.578358 -0.676359
Grease (1978)                           3.975265  3.367041 -0.608224
Little Women (1994)                     3.870588  3.321739 -0.548849
Steel Magnolias (1989)                  3.901734  3.365957 -0.535777
...                                          ...       ...       ...
Cable Guy, The (1996)                   2.250000  2.863787  0.613787
Longest Day, The (1962)                 3.411765  4.031447  0.619682
Dumb & Dumber (1994)                    2.697987  3.336595  0.638608
Kentucky Fried Movie, The (1977)        2.878788  3.555147  0.676359
Good, The Bad and The Ugly, The (1966)  3.494949  4.221300  0.726351

[1216 rows x 3 columns]

In [25]:
sorted_by_diff[::-1]

gender                                         F         M      diff
title
Good, The Bad and The Ugly, The (1966)  3.494949  4.221300  0.726351
Kentucky Fried Movie, The (1977)        2.878788  3.555147  0.676359
Dumb & Dumber (1994)                    2.697987  3.336595  0.638608
Longest Day, The (1962)                 3.411765  4.031447  0.619682
Cable Guy, The (1996)                   2.250000  2.863787  0.613787
...                                          ...       ...       ...
Steel Magnolias (1989)                  3.901734  3.365957 -0.535777
Little Women (1994)                     3.870588  3.321739 -0.548849
Grease (1978)                           3.975265  3.367041 -0.608224
Jumpin' Jack Flash (1986)               3.254717  2.578358 -0.676359
Dirty Dancing (1987)                    3.790378  2.959596 -0.830782

[1216 rows x 3 columns]

In [26]:
#find the movies that have the largest rating difference independent of gender
rating_std_by_title = data.groupby('title')['rating'].std()

In [30]:
rating_std_by_title.loc[active_titles].sort_values(ascending=False)

title
Dumb & Dumber (1994)                     1.321333
Blair Witch Project, The (1999)          1.316368
Natural Born Killers (1994)              1.307198
Tank Girl (1995)                         1.277695
Rocky Horror Picture Show, The (1975)    1.260177
                                           ...
Wrong Trousers, The (1993)               0.708666
Shawshank Redemption, The (1994)         0.700443
Great Escape, The (1963)                 0.692585
Rear Window (1954)                       0.688946
Close Shave, A (1995)                    0.667143
Name: rating, Length: 1216, dtype: float64