In [2]:
!cat ../examples/ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../examples/ex1.csv")

In [5]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [6]:
!cat ../examples/ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [7]:
pd.read_csv('../examples/ex2.csv', header= None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [8]:
pd.read_csv("../examples/ex2.csv", names=["a", "b", "c", "d", "message"],index_col= "message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [9]:
parsed = pd.read_csv("../examples/csv_mindex.csv", index_col= ["key1", "key2"])

In [10]:
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [11]:
pd.options.display.max_rows = 10

In [12]:
result = pd.read_csv("../examples/ex6.csv")

In [13]:
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [14]:
chunker = pd.read_csv("../examples/ex6.csv", chunksize= 1000)

In [15]:
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [16]:
chunker = pd.read_csv("../examples/ex6.csv", chunksize=1000)
tot = pd.Series([], dtype= 'int64')
for piece in chunker:
    tot= tot.add(piece["key"].value_counts(), fill_value= 0)
tot = tot.sort_values(ascending= False)

In [17]:
tot

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
     ...
5    157.0
2    152.0
0    151.0
9    150.0
1    146.0
Length: 36, dtype: float64

In [18]:
data = pd.read_csv("../examples/ex5.csv")

In [19]:
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [20]:
data.to_csv("../examples/out.csv")

In [21]:
!cat ../examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [22]:
import sys

In [23]:
data.to_csv(sys.stdout, sep= "|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [24]:
data.to_csv(sys.stdout, na_rep= "NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [25]:
data.to_csv(sys.stdout, header= False, index= False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [26]:
data.to_csv(sys.stdout, index= False, columns= ["a", "b"])

a,b
1,2
5,6
9,10

In [27]:
 !cat ../examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [28]:
import csv

In [29]:
f = open("../examples/ex7.csv")

In [30]:
reader = csv.reader(f)

In [31]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [32]:
f.close()

In [33]:
with open("../examples/ex7.csv") as f:
    lines = list(csv.reader(f))

In [34]:
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [35]:
header, values = lines[0], lines[1:]

In [36]:
header

['a', 'b', 'c']

In [37]:
values

[['1', '2', '3'], ['1', '2', '3']]

In [38]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

In [39]:
obj

'\n{"name": "Wes",\n "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],\n "pet": null,\n "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},\n              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]\n}\n'

In [40]:
import json

In [41]:
result = json.loads(obj)

In [42]:
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [43]:
asjson = json.dumps(result)

In [44]:
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [45]:
siblings = pd.DataFrame(result["siblings"], columns= ["name", "age"])

In [46]:
siblings

    name  age
0  Scott   34
1  Katie   42

In [47]:
!cat ../examples/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [48]:
data = pd.read_json("../examples/example.json")

In [49]:
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [50]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [51]:
tables = pd.read_html("../examples/fdic_failed_bank_list.html")

In [52]:
len(tables)

1

In [53]:
tables

[                             Bank Name             City  ST   CERT  \
 0                          Allied Bank         Mulberry  AR     91
 1         The Woodbury Banking Company         Woodbury  GA  11297
 2               First CornerStone Bank  King of Prussia  PA  35312
 3                   Trust Company Bank          Memphis  TN   9956
 4           North Milwaukee State Bank        Milwaukee  WI  20364
 ..                                 ...              ...  ..    ...
 542                 Superior Bank, FSB         Hinsdale  IL  32646
 543                Malta National Bank            Malta  OH   6629
 544    First Alliance Bank & Trust Co.       Manchester  NH  34264
 545  National State Bank of Metropolis       Metropolis  IL   3815
 546                   Bank of Honolulu         Honolulu  HI  21029

                    Acquiring Institution        Closing Date  \
 0                           Today's Bank  September 23, 2016
 1                            United Bank     August 19, 2016
 2    First-Citizens Bank & Trust Company         May 6, 2016
 3             The Bank of Fayette County      April 29, 2016
 4    First-Citizens Bank & Trust Company      March 11, 2016
 ..                                   ...                 ...
 542                Superior Federal, FSB       July 27, 2001
 543                    North Valley Bank         May 3, 2001
 544  Southern New Hampshire Bank & Trust    February 2, 2001
 545              Banterra Bank of Marion   December 14, 2000
 546                   Bank of the Orient    October 13, 2000

           Updated Date
 0    November 17, 2016
 1    November 17, 2016
 2    September 6, 2016
 3    September 6, 2016
 4        June 16, 2016
 ..                 ...
 542    August 19, 2014
 543  November 18, 2002
 544  February 18, 2003
 545     March 17, 2005
 546     March 17, 2005

 [547 rows x 7 columns]]

In [54]:
type(tables)

list

In [55]:
failures = tables[0]

In [56]:
type(failures)

pandas.core.frame.DataFrame

In [57]:
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [58]:
close_timestamps = pd.to_datetime(failures['Closing Date'])

In [59]:
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, Length: 15, dtype: int64

In [60]:
from lxml import objectify

In [61]:
path = '../datasets/mta_perf/Performance_MNR.xml'

In [62]:
with open(path) as f:
    parsed = objectify.parse(f)

In [63]:
root = parsed.getroot()

In [64]:
root

In [65]:
data = []

skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
               "DESIRED_CHANGE", "DECIMAL_PLACES"]

for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)

In [66]:
data[0]

{'AGENCY_NAME': 'Metro-North Railroad',
 'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
 'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
 'PERIOD_YEAR': 2008,
 'PERIOD_MONTH': 1,
 'CATEGORY': 'Service Indicators',
 'FREQUENCY': 'M',
 'INDICATOR_UNIT': '%',
 'YTD_TARGET': 95.0,
 'YTD_ACTUAL': 96.9,
 'MONTHLY_TARGET': 95.0,
 'MONTHLY_ACTUAL': 96.9}

In [67]:
perf = pd.DataFrame(data)

In [68]:
perf

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8
...,...,...,...,...,...,...,...,...,...,...,...,...
643,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,8,Service Indicators,M,%,97.0,,97.0,
644,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,9,Service Indicators,M,%,97.0,,97.0,
645,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,10,Service Indicators,M,%,97.0,,97.0,
646,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,11,Service Indicators,M,%,97.0,,97.0,
647,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,12,Service Indicators,M,%,97.0,,97.0,

In [69]:
perf2 = pd.read_xml(path)

In [70]:
perf2

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,8,Service Indicators,M,U,%,1,97.00,None,97.00,None
644,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,9,Service Indicators,M,U,%,1,97.00,None,97.00,None
645,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,10,Service Indicators,M,U,%,1,97.00,None,97.00,None
646,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,11,Service Indicators,M,U,%,1,97.00,None,97.00,None
647,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,12,Service Indicators,M,U,%,1,97.00,None,97.00,None

In [71]:
frame = pd.read_csv("../examples/ex1.csv")

In [72]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [73]:
frame.to_pickle("../examples/frame_pickle")

In [74]:
pd.read_pickle("../examples/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [75]:
xlsx = pd.ExcelFile('../examples/ex1.xlsx')

In [76]:
xlsx.sheet_names

['Sheet1']

In [77]:
xlsx.parse(sheet_name= 'Sheet1', index_col= 0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [78]:
frame = pd.read_excel('../examples/ex1.xlsx', sheet_name= 'Sheet1', index_col= 0)

In [79]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [80]:
writer = pd.ExcelWriter('./ex2.xlsx')

In [81]:
frame.to_excel(writer, sheet_name='Sheet1')

In [82]:
writer.close()

In [83]:
frame.to_excel('./ex2_2.xlsx')

In [84]:
frame = pd.DataFrame({"a": np.random.standard_normal(100)})

In [85]:
frame

           a
0  -1.394187
1   0.283298
2   0.546359
3  -0.174559
4  -0.373642
..       ...
95  0.165118
96  1.255364
97  0.854884
98 -0.778739
99  0.023486

[100 rows x 1 columns]

In [88]:
frame.to_hdf('./mydata.h5', key= 'obj3', format = 'table')

In [90]:
pd.read_hdf('./mydata.h5', 'obj3', where = ['index <5'])

          a
0 -1.394187
1  0.283298
2  0.546359
3 -0.174559
4 -0.373642

In [91]:
import os
os.remove('./mydata.h5')

In [92]:
import requests

In [93]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [94]:
resp = requests.get(url)

In [96]:
resp.raise_for_status()

In [97]:
data = resp.json()

In [102]:
len(data)

30

In [103]:
issues = pd.DataFrame(data, columns= ["number", "title",
   .....:                                      "labels", "state"])

In [104]:
issues

,number,title,labels,state
0,62127,#61382: FIX MultiIndex.difference for pyarrow-...,[],open
1,62121,BUG: Addition of __set_module__ breaks PyCharm...,[],open
2,62119,PERF: Importing pandas_parser lib takes 50MB o...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
3,62118,Switch default string storage from python to p...,"[{'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUy...",open
4,62117,fix(dtypes): ensure consistent behavior of is_...,[],open
...,...,...,...,...
25,62082,DOC: clarify Series alignment when assigning t...,[],open
26,62081,BUG: Series.round with pd.NA no longer raises;...,[],open
27,62080,BUG: creating Categorical from pandas Index/Se...,[],open
28,62079,DOC: Add docstring for asarray_tuplesafe in co...,[],open
29,62078,DOC: Validate docstrings for tseries.offsets.B...,[],open

In [105]:
import sqlite3

In [106]:
query = """
   .....: CREATE TABLE test
   .....: (a VARCHAR(20), b VARCHAR(20),
   .....:  c REAL,        d INTEGER
   .....: );"""

In [107]:
con = sqlite3.connect('mydata.sqlite')

In [108]:
con.execute(query)

In [109]:
con.commit()

In [110]:
data = [("Atlanta", "Georgia", 1.25, 6),
   .....:         ("Tallahassee", "Florida", 2.6, 3),
   .....:         ("Sacramento", "California", 1.7, 5)]

In [111]:
data

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [112]:
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

In [113]:
con.executemany(stmt, data)

In [114]:
con.commit()

In [115]:
cursor = con.execute("SELECT * FROM test")

In [116]:
rows = cursor.fetchall()

In [117]:
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [118]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [119]:
pd.DataFrame(rows, columns= [x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [120]:
import sqlalchemy as sqla

In [121]:
db = sqla.create_engine("sqlite:///mydata.sqlite")

In [122]:
pd.read_sql('SELECT * FROM test', db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5